-- AUTOGENERADO por scripts/generate-supabase-seed.mjs

insert into public.characters (
  id,
  name,
  anime,
  genre,
  debut_year,
  studio,
  role,
  gender,
  race,
  debut_info,
  image_url,
  age_debut_group,
  age_main_group,
  active
)
values
(
  'goku',
  'Goku',
  'Dragon Ball',
  'Shonen',
  1984,
  'Toei Animation',
  'Protagonista',
  'Masculino',
  'Saiyajin',
  'Aparece por primera vez en el capítulo 1 del manga de Dragon Ball.',
  '/images/goku.png',
  'Niño',
  'Adulto',
  true
),
(
  'vegeta',
  'Vegeta',
  'Dragon Ball',
  'Shonen',
  1988,
  'Toei Animation',
  'Deuteragonista',
  'Masculino',
  'Saiyajin',
  'Príncipe de los saiyajin, aparece como rival y enemigo de Goku antes de unirse a los Guerreros Z.',
  '/images/vegeta.png',
  'Adulto',
  'Adulto',
  true
),
(
  'naruto',
  'Naruto',
  'Naruto',
  'Shonen',
  1999,
  'Studio Pierrot',
  'Protagonista',
  'Masculino',
  'Humano',
  'Debuta en el capítulo 1 del manga, como el ninja problemático de la aldea.',
  '/images/naruto.png',
  'Adolescente',
  'Joven',
  true
),
(
  'luffy',
  'Luffy',
  'One Piece',
  'Shonen',
  1997,
  'Toei Animation',
  'Protagonista',
  'Masculino',
  'Humano',
  'Lo vemos por primera vez en el capítulo 1 del manga, dentro de un barril.',
  '/images/luffy.png',
  'Adolescente',
  'Joven',
  true
),
(
  'ichigo',
  'Ichigo',
  'Bleach',
  'Shonen',
  2001,
  'Studio Pierrot',
  'Protagonista',
  'Masculino',
  'Humano',
  'Ichigo Kurosaki debuta como un estudiante que puede ver espíritus y obtiene poderes de shinigami.',
  '/images/ichigo.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'edward_elric',
  'Edward Elric',
  'Fullmetal Alchemist',
  'Shonen',
  2001,
  'Bones',
  'Protagonista',
  'Masculino',
  'Humano',
  'El joven alquimista estatal que busca recuperar el cuerpo de su hermano tras un fallo en una transmutación prohibida.',
  '/images/edward_elric.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'tanjiro',
  'Tanjiro',
  'Kimetsu no Yaiba',
  'Shonen',
  2016,
  'Ufotable',
  'Protagonista',
  'Masculino',
  'Humano',
  'Tanjiro Kamado debuta como un chico que pierde a su familia y decide convertirse en cazador de demonios.',
  '/images/tanjiro.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'deku',
  'Deku',
  'My Hero Academia',
  'Shonen',
  2014,
  'Bones',
  'Protagonista',
  'Masculino',
  'Humano',
  'Izuku Midoriya, un chico sin poderes en un mundo de héroes, hereda el One For All.',
  '/images/deku.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'light_yagami',
  'Light Yagami',
  'Death Note',
  'Otros',
  2003,
  'Madhouse',
  'Protagonista',
  'Masculino',
  'Humano',
  'Estudiante ejemplar que encuentra un cuaderno con el poder de matar a quien tenga su nombre escrito.',
  '/images/light_yagami.png',
  'Adolescente',
  'Joven',
  true
),
(
  'lelouch',
  'Lelouch',
  'Code Geass',
  'Otros',
  2006,
  'Sunrise',
  'Protagonista',
  'Masculino',
  'Humano',
  'Príncipe exiliado que obtiene el poder del Geass y lidera una rebelión usando el alias Zero.',
  '/images/lelouch.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'spike',
  'Spike Spiegel',
  'Cowboy Bebop',
  'Otros',
  1998,
  'Sunrise',
  'Protagonista',
  'Masculino',
  'Humano',
  'Cazarrecompensas relajado y letal, con un pasado oscuro ligado al sindicato criminal.',
  '/images/spike.png',
  'Adulto',
  'Adulto',
  true
),
(
  'sakuragi',
  'Sakuragi',
  'Slam Dunk',
  'Deportes',
  1990,
  'Toei Animation',
  'Protagonista',
  'Masculino',
  'Humano',
  'Hanamichi Sakuragi aparece en el capítulo 1, rechazado por una chica y metido en peleas.',
  '/images/sakuragi.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'rukawa',
  'Rukawa',
  'Slam Dunk',
  'Deportes',
  1990,
  'Toei Animation',
  'Deuteragonista',
  'Masculino',
  'Humano',
  'Kaede Rukawa es el talentoso rival de Sakuragi en el Shohoku, frío y centrado en el básquetbol.',
  '/images/rukawa.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'hinata',
  'Hinata',
  'Haikyuu!!',
  'Deportes',
  2012,
  'Production I.G',
  'Protagonista',
  'Masculino',
  'Humano',
  'Shoyo Hinata debuta como el pequeño atacante apasionado por el vóleibol.',
  '/images/hinata.png',
  'Adolescente',
  'Joven',
  true
),
(
  'kageyama',
  'Kageyama',
  'Haikyuu!!',
  'Deportes',
  2012,
  'Production I.G',
  'Deuteragonista',
  'Masculino',
  'Humano',
  'Tobio Kageyama es el talentoso colocador apodado el “Rey de la cancha”.',
  '/images/kageyama.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'taiga',
  'Taiga',
  'Toradora!',
  'Romance',
  2006,
  'J.C.Staff',
  'Protagonista',
  'Femenino',
  'Humano',
  'Taiga Aisaka aparece como la “Tigre de Bolsillo”, conocida por su mal carácter.',
  '/images/taiga.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'kaguya',
  'Kaguya',
  'Kaguya-sama: Love is War',
  'Romance',
  2015,
  'A-1 Pictures',
  'Protagonista',
  'Femenino',
  'Humano',
  'Kaguya Shinomiya es la vicepresidenta del consejo estudiantil que compite en juegos mentales de amor con Shirogane.',
  '/images/kaguya.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'usagi',
  'Usagi',
  'Sailor Moon',
  'Otros',
  1991,
  'Toei Animation',
  'Protagonista',
  'Femenino',
  'Humano',
  'Usagi Tsukino debuta como una estudiante torpe que descubre que es Sailor Moon.',
  '/images/usagi.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'zero_two',
  'Zero Two',
  'Darling in the Franxx',
  'Otros',
  2018,
  'Trigger / A-1 Pictures',
  'Deuteragonista',
  'Femenino',
  'Otro',
  'Piloto misteriosa con cuernos rojos, conocida como el “monstruo” que nadie quiere como pareja… hasta Hiro.',
  '/images/zero_two.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'gohan',
  'Gohan',
  'Dragon Ball',
  'Shonen',
  1988,
  'Toei Animation',
  'Deuteragonista',
  'Masculino',
  'Saiyajin',
  'Personaje de Dragon Ball.',
  '/images/gohan.png',
  'Niño',
  'Adolescente',
  true
),
(
  'piccolo',
  'Piccolo',
  'Dragon Ball',
  'Shonen',
  1984,
  'Toei Animation',
  'Secundario',
  'Masculino',
  'Otro',
  'Personaje de Dragon Ball.',
  '/images/piccolo.png',
  'Adulto',
  'Adulto',
  true
),
(
  'freezer',
  'Freezer',
  'Dragon Ball',
  'Shonen',
  1984,
  'Toei Animation',
  'Antagonista',
  'Otro',
  'Alien',
  'Personaje de Dragon Ball.',
  '/images/freezer.png',
  'Adulto',
  'Adulto',
  true
),
(
  'cell',
  'Cell',
  'Dragon Ball',
  'Shonen',
  1984,
  'Toei Animation',
  'Antagonista',
  'Masculino',
  'Androide',
  'Personaje de Dragon Ball.',
  '/images/cell.png',
  'Adulto',
  'Adulto',
  true
),
(
  'trunks',
  'Trunks',
  'Dragon Ball',
  'Shonen',
  1984,
  'Toei Animation',
  'Secundario',
  'Masculino',
  'Saiyajin',
  'Personaje de Dragon Ball.',
  '/images/trunks.png',
  'Joven',
  'Joven',
  true
),
(
  'bulma',
  'Bulma',
  'Dragon Ball',
  'Shonen',
  1984,
  'Toei Animation',
  'Secundario',
  'Femenino',
  'Humano',
  'Personaje de Dragon Ball.',
  '/images/bulma.png',
  'Joven',
  'Adulto',
  true
),
(
  'krillin',
  'Krillin',
  'Dragon Ball',
  'Shonen',
  1984,
  'Toei Animation',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Dragon Ball.',
  '/images/krillin.png',
  'Adolescente',
  'Adulto',
  true
),
(
  'majin_buu',
  'Majin Buu',
  'Dragon Ball',
  'Shonen',
  1984,
  'Toei Animation',
  'Antagonista',
  'Masculino',
  'Demonio',
  'Personaje de Dragon Ball.',
  '/images/majin_buu.png',
  'Adulto',
  'Adulto',
  true
),
(
  'beerus',
  'Beerus',
  'Dragon Ball',
  'Shonen',
  1984,
  'Toei Animation',
  'Secundario',
  'Masculino',
  'Dios',
  'Personaje de Dragon Ball.',
  '/images/beerus.png',
  'Mayor',
  'Mayor',
  true
),
(
  'whis',
  'Whis',
  'Dragon Ball',
  'Shonen',
  1984,
  'Toei Animation',
  'Secundario',
  'Masculino',
  'Angel',
  'Personaje de Dragon Ball.',
  '/images/whis.png',
  'Mayor',
  'Mayor',
  true
),
(
  'roronoa_zoro',
  'Roronoa Zoro',
  'One Piece',
  'Shonen',
  1997,
  'Toei Animation',
  'Deuteragonista',
  'Masculino',
  'Humano',
  'Personaje de One Piece.',
  '/images/roronoa_zoro.png',
  'Joven',
  'Joven',
  true
),
(
  'nami',
  'Nami',
  'One Piece',
  'Shonen',
  1997,
  'Toei Animation',
  'Secundario',
  'Femenino',
  'Humano',
  'Personaje de One Piece.',
  '/images/nami.png',
  'Joven',
  'Joven',
  true
),
(
  'sanji',
  'Sanji',
  'One Piece',
  'Shonen',
  1997,
  'Toei Animation',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de One Piece.',
  '/images/sanji.png',
  'Joven',
  'Joven',
  true
),
(
  'usopp',
  'Usopp',
  'One Piece',
  'Shonen',
  1997,
  'Toei Animation',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de One Piece.',
  '/images/usopp.png',
  'Adolescente',
  'Joven',
  true
),
(
  'tony_tony_chopper',
  'Tony Tony Chopper',
  'One Piece',
  'Shonen',
  1997,
  'Toei Animation',
  'Secundario',
  'Masculino',
  'Otro',
  'Personaje de One Piece.',
  '/images/tony_tony_chopper.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'nico_robin',
  'Nico Robin',
  'One Piece',
  'Shonen',
  1997,
  'Toei Animation',
  'Secundario',
  'Femenino',
  'Humano',
  'Personaje de One Piece.',
  '/images/nico_robin.png',
  'Adulto',
  'Adulto',
  true
),
(
  'franky',
  'Franky',
  'One Piece',
  'Shonen',
  1997,
  'Toei Animation',
  'Secundario',
  'Masculino',
  'Cyborg',
  'Personaje de One Piece.',
  '/images/franky.png',
  'Adulto',
  'Adulto',
  true
),
(
  'brook',
  'Brook',
  'One Piece',
  'Shonen',
  1997,
  'Toei Animation',
  'Secundario',
  'Masculino',
  'Otro',
  'Personaje de One Piece.',
  '/images/brook.png',
  'Adulto',
  'Adulto',
  true
),
(
  'jinbe',
  'Jinbe',
  'One Piece',
  'Shonen',
  1997,
  'Toei Animation',
  'Secundario',
  'Masculino',
  'Otro',
  'Personaje de One Piece.',
  '/images/jinbe.png',
  'Adulto',
  'Adulto',
  true
),
(
  'portgas_d_ace',
  'Portgas D. Ace',
  'One Piece',
  'Shonen',
  1997,
  'Toei Animation',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de One Piece.',
  '/images/portgas_d_ace.png',
  'Joven',
  'Joven',
  true
),
(
  'trafalgar_law',
  'Trafalgar Law',
  'One Piece',
  'Shonen',
  1997,
  'Toei Animation',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de One Piece.',
  '/images/trafalgar_law.png',
  'Adulto',
  'Adulto',
  true
),
(
  'shanks',
  'Shanks',
  'One Piece',
  'Shonen',
  1997,
  'Toei Animation',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de One Piece.',
  '/images/shanks.png',
  'Adulto',
  'Adulto',
  true
),
(
  'marshall_d_teach',
  'Marshall D. Teach',
  'One Piece',
  'Shonen',
  1997,
  'Toei Animation',
  'Antagonista',
  'Masculino',
  'Humano',
  'Personaje de One Piece.',
  '/images/marshall_d_teach.png',
  'Adulto',
  'Adulto',
  true
),
(
  'boa_hancock',
  'Boa Hancock',
  'One Piece',
  'Shonen',
  1997,
  'Toei Animation',
  'Secundario',
  'Femenino',
  'Humano',
  'Personaje de One Piece.',
  '/images/boa_hancock.png',
  'Adulto',
  'Adulto',
  true
),
(
  'sabo',
  'Sabo',
  'One Piece',
  'Shonen',
  1997,
  'Toei Animation',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de One Piece.',
  '/images/sabo.png',
  'Joven',
  'Joven',
  true
),
(
  'donquixote_doflamingo',
  'Donquixote Doflamingo',
  'One Piece',
  'Shonen',
  1997,
  'Toei Animation',
  'Antagonista',
  'Masculino',
  'Humano',
  'Personaje de One Piece.',
  '/images/donquixote_doflamingo.png',
  'Adulto',
  'Adulto',
  true
),
(
  'kaido',
  'Kaido',
  'One Piece',
  'Shonen',
  1997,
  'Toei Animation',
  'Antagonista',
  'Masculino',
  'Otro',
  'Personaje de One Piece.',
  '/images/kaido.png',
  'Mayor',
  'Mayor',
  true
),
(
  'big_mom',
  'Big Mom',
  'One Piece',
  'Shonen',
  1997,
  'Toei Animation',
  'Antagonista',
  'Femenino',
  'Humano',
  'Personaje de One Piece.',
  '/images/big_mom.png',
  'Mayor',
  'Mayor',
  true
),
(
  'sasuke_uchiha',
  'Sasuke Uchiha',
  'Naruto',
  'Shonen',
  1999,
  'Studio Pierrot',
  'Deuteragonista',
  'Masculino',
  'Humano',
  'Personaje de Naruto.',
  '/images/sasuke_uchiha.png',
  'Adolescente',
  'Joven',
  true
),
(
  'sakura_haruno',
  'Sakura Haruno',
  'Naruto',
  'Shonen',
  1999,
  'Studio Pierrot',
  'Secundario',
  'Femenino',
  'Humano',
  'Personaje de Naruto.',
  '/images/sakura_haruno.png',
  'Adolescente',
  'Joven',
  true
),
(
  'kakashi_hatake',
  'Kakashi Hatake',
  'Naruto',
  'Shonen',
  1999,
  'Studio Pierrot',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Naruto.',
  '/images/kakashi_hatake.png',
  'Adulto',
  'Adulto',
  true
),
(
  'itachi_uchiha',
  'Itachi Uchiha',
  'Naruto',
  'Shonen',
  1999,
  'Studio Pierrot',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Naruto.',
  '/images/itachi_uchiha.png',
  'Adulto',
  'Adulto',
  true
),
(
  'gaara',
  'Gaara',
  'Naruto',
  'Shonen',
  1999,
  'Studio Pierrot',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Naruto.',
  '/images/gaara.png',
  'Adolescente',
  'Adulto',
  true
),
(
  'jiraiya',
  'Jiraiya',
  'Naruto',
  'Shonen',
  1999,
  'Studio Pierrot',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Naruto.',
  '/images/jiraiya.png',
  'Adulto',
  'Mayor',
  true
),
(
  'orochimaru',
  'Orochimaru',
  'Naruto',
  'Shonen',
  1999,
  'Studio Pierrot',
  'Antagonista',
  'Masculino',
  'Humano',
  'Personaje de Naruto.',
  '/images/orochimaru.png',
  'Adulto',
  'Mayor',
  true
),
(
  'pain',
  'Pain',
  'Naruto',
  'Shonen',
  1999,
  'Studio Pierrot',
  'Antagonista',
  'Masculino',
  'Humano',
  'Personaje de Naruto.',
  '/images/pain.png',
  'Adulto',
  'Adulto',
  true
),
(
  'madara_uchiha',
  'Madara Uchiha',
  'Naruto',
  'Shonen',
  1999,
  'Studio Pierrot',
  'Antagonista',
  'Masculino',
  'Humano',
  'Personaje de Naruto.',
  '/images/madara_uchiha.png',
  'Mayor',
  'Mayor',
  true
),
(
  'obito_uchiha',
  'Obito Uchiha',
  'Naruto',
  'Shonen',
  1999,
  'Studio Pierrot',
  'Antagonista',
  'Masculino',
  'Humano',
  'Personaje de Naruto.',
  '/images/obito_uchiha.png',
  'Adulto',
  'Adulto',
  true
),
(
  'tsunade',
  'Tsunade',
  'Naruto',
  'Shonen',
  1999,
  'Studio Pierrot',
  'Secundario',
  'Femenino',
  'Humano',
  'Personaje de Naruto.',
  '/images/tsunade.png',
  'Adulto',
  'Mayor',
  true
),
(
  'shikamaru_nara',
  'Shikamaru Nara',
  'Naruto',
  'Shonen',
  1999,
  'Studio Pierrot',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Naruto.',
  '/images/shikamaru_nara.png',
  'Adolescente',
  'Adulto',
  true
),
(
  'rukia_kuchiki',
  'Rukia Kuchiki',
  'Bleach',
  'Shonen',
  2001,
  'Studio Pierrot',
  'Deuteragonista',
  'Femenino',
  'Shinigami',
  'Personaje de Bleach.',
  '/images/rukia_kuchiki.png',
  'Adolescente',
  'Joven',
  true
),
(
  'sosuke_aizen',
  'Sosuke Aizen',
  'Bleach',
  'Shonen',
  2001,
  'Studio Pierrot',
  'Antagonista',
  'Masculino',
  'Shinigami',
  'Personaje de Bleach.',
  '/images/sosuke_aizen.png',
  'Adulto',
  'Adulto',
  true
),
(
  'renji_abarai',
  'Renji Abarai',
  'Bleach',
  'Shonen',
  2001,
  'Studio Pierrot',
  'Secundario',
  'Masculino',
  'Shinigami',
  'Personaje de Bleach.',
  '/images/renji_abarai.png',
  'Joven',
  'Joven',
  true
),
(
  'byakuya_kuchiki',
  'Byakuya Kuchiki',
  'Bleach',
  'Shonen',
  2001,
  'Studio Pierrot',
  'Secundario',
  'Masculino',
  'Shinigami',
  'Personaje de Bleach.',
  '/images/byakuya_kuchiki.png',
  'Adulto',
  'Adulto',
  true
),
(
  'orihime_inoue',
  'Orihime Inoue',
  'Bleach',
  'Shonen',
  2001,
  'Studio Pierrot',
  'Secundario',
  'Femenino',
  'Humano',
  'Personaje de Bleach.',
  '/images/orihime_inoue.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'uryu_ishida',
  'Uryu Ishida',
  'Bleach',
  'Shonen',
  2001,
  'Studio Pierrot',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Bleach.',
  '/images/uryu_ishida.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'kenpachi_zaraki',
  'Kenpachi Zaraki',
  'Bleach',
  'Shonen',
  2001,
  'Studio Pierrot',
  'Secundario',
  'Masculino',
  'Shinigami',
  'Personaje de Bleach.',
  '/images/kenpachi_zaraki.png',
  'Adulto',
  'Adulto',
  true
),
(
  'toshiro_hitsugaya',
  'Toshiro Hitsugaya',
  'Bleach',
  'Shonen',
  2001,
  'Studio Pierrot',
  'Secundario',
  'Masculino',
  'Shinigami',
  'Personaje de Bleach.',
  '/images/toshiro_hitsugaya.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'yoruichi_shihoin',
  'Yoruichi Shihoin',
  'Bleach',
  'Shonen',
  2001,
  'Studio Pierrot',
  'Secundario',
  'Femenino',
  'Shinigami',
  'Personaje de Bleach.',
  '/images/yoruichi_shihoin.png',
  'Adulto',
  'Adulto',
  true
),
(
  'nezuko_kamado',
  'Nezuko Kamado',
  'Kimetsu no Yaiba',
  'Shonen',
  2016,
  'Ufotable',
  'Deuteragonista',
  'Femenino',
  'Demonio',
  'Personaje de Kimetsu no Yaiba.',
  '/images/nezuko_kamado.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'zenitsu_agatsuma',
  'Zenitsu Agatsuma',
  'Kimetsu no Yaiba',
  'Shonen',
  2016,
  'Ufotable',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Kimetsu no Yaiba.',
  '/images/zenitsu_agatsuma.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'inosuke_hashibira',
  'Inosuke Hashibira',
  'Kimetsu no Yaiba',
  'Shonen',
  2016,
  'Ufotable',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Kimetsu no Yaiba.',
  '/images/inosuke_hashibira.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'giyu_tomioka',
  'Giyu Tomioka',
  'Kimetsu no Yaiba',
  'Shonen',
  2016,
  'Ufotable',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Kimetsu no Yaiba.',
  '/images/giyu_tomioka.png',
  'Adulto',
  'Adulto',
  true
),
(
  'shinobu_kocho',
  'Shinobu Kocho',
  'Kimetsu no Yaiba',
  'Shonen',
  2016,
  'Ufotable',
  'Secundario',
  'Femenino',
  'Humano',
  'Personaje de Kimetsu no Yaiba.',
  '/images/shinobu_kocho.png',
  'Adulto',
  'Adulto',
  true
),
(
  'muzan_kibutsuji',
  'Muzan Kibutsuji',
  'Kimetsu no Yaiba',
  'Shonen',
  2016,
  'Ufotable',
  'Antagonista',
  'Masculino',
  'Demonio',
  'Personaje de Kimetsu no Yaiba.',
  '/images/muzan_kibutsuji.png',
  'Adulto',
  'Mayor',
  true
),
(
  'izuku_midoriya',
  'Izuku Midoriya',
  'My Hero Academia',
  'Shonen',
  2014,
  'Bones',
  'Protagonista',
  'Masculino',
  'Humano',
  'Personaje de My Hero Academia.',
  '/images/izuku_midoriya.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'katsuki_bakugo',
  'Katsuki Bakugo',
  'My Hero Academia',
  'Shonen',
  2014,
  'Bones',
  'Deuteragonista',
  'Masculino',
  'Humano',
  'Personaje de My Hero Academia.',
  '/images/katsuki_bakugo.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'shoto_todoroki',
  'Shoto Todoroki',
  'My Hero Academia',
  'Shonen',
  2014,
  'Bones',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de My Hero Academia.',
  '/images/shoto_todoroki.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'all_might',
  'All Might',
  'My Hero Academia',
  'Shonen',
  2014,
  'Bones',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de My Hero Academia.',
  '/images/all_might.png',
  'Adulto',
  'Mayor',
  true
),
(
  'ochaco_uraraka',
  'Ochaco Uraraka',
  'My Hero Academia',
  'Shonen',
  2014,
  'Bones',
  'Secundario',
  'Femenino',
  'Humano',
  'Personaje de My Hero Academia.',
  '/images/ochaco_uraraka.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'shota_aizawa',
  'Shota Aizawa',
  'My Hero Academia',
  'Shonen',
  2014,
  'Bones',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de My Hero Academia.',
  '/images/shota_aizawa.png',
  'Adulto',
  'Adulto',
  true
),
(
  'tomura_shigaraki',
  'Tomura Shigaraki',
  'My Hero Academia',
  'Shonen',
  2014,
  'Bones',
  'Antagonista',
  'Masculino',
  'Humano',
  'Personaje de My Hero Academia.',
  '/images/tomura_shigaraki.png',
  'Adulto',
  'Adulto',
  true
),
(
  'dabi',
  'Dabi',
  'My Hero Academia',
  'Shonen',
  2014,
  'Bones',
  'Antagonista',
  'Masculino',
  'Humano',
  'Personaje de My Hero Academia.',
  '/images/dabi.png',
  'Adulto',
  'Adulto',
  true
),
(
  'l',
  'L',
  'Death Note',
  'Shonen',
  2003,
  'Madhouse',
  'Deuteragonista',
  'Masculino',
  'Humano',
  'Personaje de Death Note.',
  '/images/l.png',
  'Adulto',
  'Adulto',
  true
),
(
  'ryuk',
  'Ryuk',
  'Death Note',
  'Shonen',
  2003,
  'Madhouse',
  'Secundario',
  'Masculino',
  'Shinigami',
  'Personaje de Death Note.',
  '/images/ryuk.png',
  'Mayor',
  'Mayor',
  true
),
(
  'misa_amane',
  'Misa Amane',
  'Death Note',
  'Shonen',
  2003,
  'Madhouse',
  'Secundario',
  'Femenino',
  'Humano',
  'Personaje de Death Note.',
  '/images/misa_amane.png',
  'Joven',
  'Joven',
  true
),
(
  'near',
  'Near',
  'Death Note',
  'Shonen',
  2003,
  'Madhouse',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Death Note.',
  '/images/near.png',
  'Niño',
  'Adolescente',
  true
),
(
  'suzaku_kururugi',
  'Suzaku Kururugi',
  'Code Geass',
  'Otros',
  2006,
  'Sunrise',
  'Deuteragonista',
  'Masculino',
  'Humano',
  'Personaje de Code Geass.',
  '/images/suzaku_kururugi.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'c_c',
  'C.C.',
  'Code Geass',
  'Otros',
  2006,
  'Sunrise',
  'Secundario',
  'Femenino',
  'Humano',
  'Personaje de Code Geass.',
  '/images/c_c.png',
  'Mayor',
  'Mayor',
  true
),
(
  'ed',
  'Ed',
  'Cowboy Bebop',
  'Otros',
  1998,
  'Sunrise',
  'Secundario',
  'Otro',
  'Humano',
  'Personaje de Cowboy Bebop.',
  '/images/ed.png',
  'Niño',
  'Niño',
  true
),
(
  'vicious',
  'Vicious',
  'Cowboy Bebop',
  'Otros',
  1998,
  'Sunrise',
  'Antagonista',
  'Masculino',
  'Humano',
  'Personaje de Cowboy Bebop.',
  '/images/vicious.png',
  'Adulto',
  'Adulto',
  true
),
(
  'yuji_itadori',
  'Yuji Itadori',
  'Jujutsu Kaisen',
  'Shonen',
  2018,
  'MAPPA',
  'Protagonista',
  'Masculino',
  'Humano',
  'Personaje de Jujutsu Kaisen.',
  '/images/yuji_itadori.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'megumi_fushiguro',
  'Megumi Fushiguro',
  'Jujutsu Kaisen',
  'Shonen',
  2018,
  'MAPPA',
  'Deuteragonista',
  'Masculino',
  'Humano',
  'Personaje de Jujutsu Kaisen.',
  '/images/megumi_fushiguro.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'nobara_kugisaki',
  'Nobara Kugisaki',
  'Jujutsu Kaisen',
  'Shonen',
  2018,
  'MAPPA',
  'Secundario',
  'Femenino',
  'Humano',
  'Personaje de Jujutsu Kaisen.',
  '/images/nobara_kugisaki.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'satoru_gojo',
  'Satoru Gojo',
  'Jujutsu Kaisen',
  'Shonen',
  2018,
  'MAPPA',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Jujutsu Kaisen.',
  '/images/satoru_gojo.png',
  'Adulto',
  'Adulto',
  true
),
(
  'ryomen_sukuna',
  'Ryomen Sukuna',
  'Jujutsu Kaisen',
  'Shonen',
  2018,
  'MAPPA',
  'Antagonista',
  'Masculino',
  'Demonio',
  'Personaje de Jujutsu Kaisen.',
  '/images/ryomen_sukuna.png',
  'Mayor',
  'Mayor',
  true
),
(
  'suguru_geto',
  'Suguru Geto',
  'Jujutsu Kaisen',
  'Shonen',
  2018,
  'MAPPA',
  'Antagonista',
  'Masculino',
  'Humano',
  'Personaje de Jujutsu Kaisen.',
  '/images/suguru_geto.png',
  'Adulto',
  'Adulto',
  true
),
(
  'eren_yeager',
  'Eren Yeager',
  'Attack on Titan',
  'Otros',
  2009,
  'Wit Studio / MAPPA',
  'Protagonista',
  'Masculino',
  'Humano',
  'Personaje de Attack on Titan.',
  '/images/eren_yeager.png',
  'Adolescente',
  'Joven',
  true
),
(
  'mikasa_ackerman',
  'Mikasa Ackerman',
  'Attack on Titan',
  'Otros',
  2009,
  'Wit Studio / MAPPA',
  'Deuteragonista',
  'Femenino',
  'Humano',
  'Personaje de Attack on Titan.',
  '/images/mikasa_ackerman.png',
  'Adolescente',
  'Joven',
  true
),
(
  'erwin_smith',
  'Erwin Smith',
  'Attack on Titan',
  'Otros',
  2009,
  'Wit Studio / MAPPA',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Attack on Titan.',
  '/images/erwin_smith.png',
  'Adulto',
  'Adulto',
  true
),
(
  'hange_zoe',
  'Hange Zoe',
  'Attack on Titan',
  'Otros',
  2009,
  'Wit Studio / MAPPA',
  'Secundario',
  'Otro',
  'Humano',
  'Personaje de Attack on Titan.',
  '/images/hange_zoe.png',
  'Adulto',
  'Adulto',
  true
),
(
  'reiner_braun',
  'Reiner Braun',
  'Attack on Titan',
  'Otros',
  2009,
  'Wit Studio / MAPPA',
  'Antagonista',
  'Masculino',
  'Humano',
  'Personaje de Attack on Titan.',
  '/images/reiner_braun.png',
  'Adolescente',
  'Joven',
  true
),
(
  'zeke_yeager',
  'Zeke Yeager',
  'Attack on Titan',
  'Otros',
  2009,
  'Wit Studio / MAPPA',
  'Antagonista',
  'Masculino',
  'Humano',
  'Personaje de Attack on Titan.',
  '/images/zeke_yeager.png',
  'Adulto',
  'Adulto',
  true
),
(
  'roy_mustang',
  'Roy Mustang',
  'Fullmetal Alchemist',
  'Shonen',
  2001,
  'Bones',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Fullmetal Alchemist.',
  '/images/roy_mustang.png',
  'Adulto',
  'Adulto',
  true
),
(
  'scar',
  'Scar',
  'Fullmetal Alchemist',
  'Shonen',
  2001,
  'Bones',
  'Antagonista',
  'Masculino',
  'Humano',
  'Personaje de Fullmetal Alchemist.',
  '/images/scar.png',
  'Adulto',
  'Adulto',
  true
),
(
  'gon_freecss',
  'Gon Freecss',
  'Hunter x Hunter',
  'Shonen',
  1998,
  'Madhouse',
  'Protagonista',
  'Masculino',
  'Humano',
  'Personaje de Hunter x Hunter.',
  '/images/gon_freecss.png',
  'Niño',
  'Niño',
  true
),
(
  'kurapika',
  'Kurapika',
  'Hunter x Hunter',
  'Shonen',
  1998,
  'Madhouse',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Hunter x Hunter.',
  '/images/kurapika.png',
  'Adolescente',
  'Joven',
  true
),
(
  'hisoka',
  'Hisoka',
  'Hunter x Hunter',
  'Shonen',
  1998,
  'Madhouse',
  'Antagonista',
  'Masculino',
  'Humano',
  'Personaje de Hunter x Hunter.',
  '/images/hisoka.png',
  'Adulto',
  'Adulto',
  true
),
(
  'meruem',
  'Meruem',
  'Hunter x Hunter',
  'Shonen',
  1998,
  'Madhouse',
  'Antagonista',
  'Masculino',
  'Otro',
  'Personaje de Hunter x Hunter.',
  '/images/meruem.png',
  'Mayor',
  'Mayor',
  true
),
(
  'isaac_netero',
  'Isaac Netero',
  'Hunter x Hunter',
  'Shonen',
  1998,
  'Madhouse',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Hunter x Hunter.',
  '/images/isaac_netero.png',
  'Adulto',
  'Mayor',
  true
),
(
  'jonathan_joestar',
  'Jonathan Joestar',
  'JoJo''s Bizarre Adventure',
  'Shonen',
  1987,
  'David Production',
  'Protagonista',
  'Masculino',
  'Humano',
  'Personaje de JoJo''s Bizarre Adventure.',
  '/images/jonathan_joestar.png',
  'Joven',
  'Joven',
  true
),
(
  'joseph_joestar',
  'Joseph Joestar',
  'JoJo''s Bizarre Adventure',
  'Shonen',
  1987,
  'David Production',
  'Protagonista',
  'Masculino',
  'Humano',
  'Personaje de JoJo''s Bizarre Adventure.',
  '/images/joseph_joestar.png',
  'Joven',
  'Mayor',
  true
),
(
  'jotaro_kujo',
  'Jotaro Kujo',
  'JoJo''s Bizarre Adventure',
  'Shonen',
  1987,
  'David Production',
  'Protagonista',
  'Masculino',
  'Humano',
  'Personaje de JoJo''s Bizarre Adventure.',
  '/images/jotaro_kujo.png',
  'Adolescente',
  'Adulto',
  true
),
(
  'dio_brando',
  'Dio Brando',
  'JoJo''s Bizarre Adventure',
  'Shonen',
  1987,
  'David Production',
  'Antagonista',
  'Masculino',
  'Otro',
  'Personaje de JoJo''s Bizarre Adventure.',
  '/images/dio_brando.png',
  'Mayor',
  'Mayor',
  true
),
(
  'josuke_higashikata',
  'Josuke Higashikata',
  'JoJo''s Bizarre Adventure',
  'Shonen',
  1987,
  'David Production',
  'Protagonista',
  'Masculino',
  'Humano',
  'Personaje de JoJo''s Bizarre Adventure.',
  '/images/josuke_higashikata.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'giorno_giovanna',
  'Giorno Giovanna',
  'JoJo''s Bizarre Adventure',
  'Shonen',
  1987,
  'David Production',
  'Protagonista',
  'Masculino',
  'Humano',
  'Personaje de JoJo''s Bizarre Adventure.',
  '/images/giorno_giovanna.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'saitama',
  'Saitama',
  'One Punch Man',
  'Shonen',
  2009,
  'Madhouse',
  'Protagonista',
  'Masculino',
  'Humano',
  'Personaje de One Punch Man.',
  '/images/saitama.png',
  'Adulto',
  'Adulto',
  true
),
(
  'genos',
  'Genos',
  'One Punch Man',
  'Shonen',
  2009,
  'Madhouse',
  'Deuteragonista',
  'Masculino',
  'Cyborg',
  'Personaje de One Punch Man.',
  '/images/genos.png',
  'Joven',
  'Joven',
  true
),
(
  'tatsumaki',
  'Tatsumaki',
  'One Punch Man',
  'Shonen',
  2009,
  'Madhouse',
  'Secundario',
  'Femenino',
  'Humano',
  'Personaje de One Punch Man.',
  '/images/tatsumaki.png',
  'Adulto',
  'Adulto',
  true
),
(
  'garou',
  'Garou',
  'One Punch Man',
  'Shonen',
  2009,
  'Madhouse',
  'Antagonista',
  'Masculino',
  'Humano',
  'Personaje de One Punch Man.',
  '/images/garou.png',
  'Joven',
  'Joven',
  true
),
(
  'king',
  'King',
  'One Punch Man',
  'Shonen',
  2009,
  'Madhouse',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de One Punch Man.',
  '/images/king.png',
  'Adulto',
  'Adulto',
  true
),
(
  'ken_kaneki',
  'Ken Kaneki',
  'Tokyo Ghoul',
  'Otros',
  2011,
  'Studio Pierrot',
  'Protagonista',
  'Masculino',
  'Ghoul',
  'Personaje de Tokyo Ghoul.',
  '/images/ken_kaneki.png',
  'Adolescente',
  'Joven',
  true
),
(
  'touka_kirishima',
  'Touka Kirishima',
  'Tokyo Ghoul',
  'Otros',
  2011,
  'Studio Pierrot',
  'Deuteragonista',
  'Femenino',
  'Ghoul',
  'Personaje de Tokyo Ghoul.',
  '/images/touka_kirishima.png',
  'Adolescente',
  'Joven',
  true
),
(
  'jason',
  'Jason',
  'Tokyo Ghoul',
  'Otros',
  2011,
  'Studio Pierrot',
  'Antagonista',
  'Masculino',
  'Ghoul',
  'Personaje de Tokyo Ghoul.',
  '/images/jason.png',
  'Adulto',
  'Adulto',
  true
),
(
  'tooru_oikawa',
  'Tooru Oikawa',
  'Haikyuu!!',
  'Deportes',
  2012,
  'Production I.G',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Haikyuu!!.',
  '/images/tooru_oikawa.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'kenma_kozume',
  'Kenma Kozume',
  'Haikyuu!!',
  'Deportes',
  2012,
  'Production I.G',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Haikyuu!!.',
  '/images/kenma_kozume.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'kei_tsukishima',
  'Kei Tsukishima',
  'Haikyuu!!',
  'Deportes',
  2012,
  'Production I.G',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Haikyuu!!.',
  '/images/kei_tsukishima.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'takenori_akagi',
  'Takenori Akagi',
  'Slam Dunk',
  'Deportes',
  1990,
  'Toei Animation',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Slam Dunk.',
  '/images/takenori_akagi.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'hisashi_mitsui',
  'Hisashi Mitsui',
  'Slam Dunk',
  'Deportes',
  1990,
  'Toei Animation',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Slam Dunk.',
  '/images/hisashi_mitsui.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'ryota_miyagi',
  'Ryota Miyagi',
  'Slam Dunk',
  'Deportes',
  1990,
  'Toei Animation',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Slam Dunk.',
  '/images/ryota_miyagi.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'tetsuya_kuroko',
  'Tetsuya Kuroko',
  'Kuroko no Basket',
  'Deportes',
  2008,
  'Production I.G',
  'Protagonista',
  'Masculino',
  'Humano',
  'Personaje de Kuroko no Basket.',
  '/images/tetsuya_kuroko.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'daiki_aomine',
  'Daiki Aomine',
  'Kuroko no Basket',
  'Deportes',
  2008,
  'Production I.G',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Kuroko no Basket.',
  '/images/daiki_aomine.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'seijuro_akashi',
  'Seijuro Akashi',
  'Kuroko no Basket',
  'Deportes',
  2008,
  'Production I.G',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Kuroko no Basket.',
  '/images/seijuro_akashi.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'miyuki_shirogane',
  'Miyuki Shirogane',
  'Kaguya-sama: Love is War',
  'Romance',
  2015,
  'A-1 Pictures',
  'Deuteragonista',
  'Masculino',
  'Humano',
  'Personaje de Kaguya-sama: Love is War.',
  '/images/miyuki_shirogane.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'chika_fujiwara',
  'Chika Fujiwara',
  'Kaguya-sama: Love is War',
  'Romance',
  2015,
  'A-1 Pictures',
  'Secundario',
  'Femenino',
  'Humano',
  'Personaje de Kaguya-sama: Love is War.',
  '/images/chika_fujiwara.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'yu_ishigami',
  'Yu Ishigami',
  'Kaguya-sama: Love is War',
  'Romance',
  2015,
  'A-1 Pictures',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Kaguya-sama: Love is War.',
  '/images/yu_ishigami.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'hiro',
  'Hiro',
  'Darling in the Franxx',
  'Romance',
  2018,
  'Trigger / A-1 Pictures',
  'Deuteragonista',
  'Masculino',
  'Humano',
  'Personaje de Darling in the Franxx.',
  '/images/hiro.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'shinji_ikari',
  'Shinji Ikari',
  'Neon Genesis Evangelion',
  'Otros',
  1995,
  'Gainax',
  'Protagonista',
  'Masculino',
  'Humano',
  'Personaje de Neon Genesis Evangelion.',
  '/images/shinji_ikari.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'misato_katsuragi',
  'Misato Katsuragi',
  'Neon Genesis Evangelion',
  'Otros',
  1995,
  'Gainax',
  'Secundario',
  'Femenino',
  'Humano',
  'Personaje de Neon Genesis Evangelion.',
  '/images/misato_katsuragi.png',
  'Adulto',
  'Adulto',
  true
),
(
  'happy',
  'Happy',
  'Fairy Tail',
  'Shonen',
  2006,
  'A-1 Pictures',
  'Secundario',
  'Masculino',
  'Otro',
  'Personaje de Fairy Tail.',
  '/images/happy.png',
  'Niño',
  'Niño',
  true
),
(
  'asta',
  'Asta',
  'Black Clover',
  'Shonen',
  2015,
  'Studio Pierrot',
  'Protagonista',
  'Masculino',
  'Humano',
  'Personaje de Black Clover.',
  '/images/asta.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'yuno',
  'Yuno',
  'Black Clover',
  'Shonen',
  2015,
  'Studio Pierrot',
  'Deuteragonista',
  'Masculino',
  'Humano',
  'Personaje de Black Clover.',
  '/images/yuno.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'rintaro_okabe',
  'Rintaro Okabe',
  'Steins;Gate',
  'Otros',
  2009,
  'White Fox',
  'Protagonista',
  'Masculino',
  'Humano',
  'Personaje de Steins;Gate.',
  '/images/rintaro_okabe.png',
  'Joven',
  'Joven',
  true
),
(
  'kurisu_makise',
  'Kurisu Makise',
  'Steins;Gate',
  'Otros',
  2009,
  'White Fox',
  'Deuteragonista',
  'Femenino',
  'Humano',
  'Personaje de Steins;Gate.',
  '/images/kurisu_makise.png',
  'Joven',
  'Joven',
  true
),
(
  'mayuri_shiina',
  'Mayuri Shiina',
  'Steins;Gate',
  'Otros',
  2009,
  'White Fox',
  'Secundario',
  'Femenino',
  'Humano',
  'Personaje de Steins;Gate.',
  '/images/mayuri_shiina.png',
  'Joven',
  'Joven',
  true
),
(
  'subaru_natsuki',
  'Subaru Natsuki',
  'Re:Zero',
  'Otros',
  2014,
  'White Fox',
  'Protagonista',
  'Masculino',
  'Humano',
  'Personaje de Re:Zero.',
  '/images/subaru_natsuki.png',
  'Adolescente',
  'Joven',
  true
),
(
  'rem',
  'Rem',
  'Re:Zero',
  'Otros',
  2014,
  'White Fox',
  'Secundario',
  'Femenino',
  'Otro',
  'Personaje de Re:Zero.',
  '/images/rem.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'ram',
  'Ram',
  'Re:Zero',
  'Otros',
  2014,
  'White Fox',
  'Secundario',
  'Femenino',
  'Otro',
  'Personaje de Re:Zero.',
  '/images/ram.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'kirito',
  'Kirito',
  'Sword Art Online',
  'Shonen',
  2009,
  'A-1 Pictures',
  'Protagonista',
  'Masculino',
  'Humano',
  'Personaje de Sword Art Online.',
  '/images/kirito.png',
  'Adolescente',
  'Joven',
  true
),
(
  'asuna',
  'Asuna',
  'Sword Art Online',
  'Shonen',
  2009,
  'A-1 Pictures',
  'Deuteragonista',
  'Femenino',
  'Humano',
  'Personaje de Sword Art Online.',
  '/images/asuna.png',
  'Adolescente',
  'Joven',
  true
),
(
  'sinon',
  'Sinon',
  'Sword Art Online',
  'Shonen',
  2009,
  'A-1 Pictures',
  'Secundario',
  'Femenino',
  'Humano',
  'Personaje de Sword Art Online.',
  '/images/sinon.png',
  'Adolescente',
  'Joven',
  true
),
(
  'saber',
  'Saber',
  'Fate/stay night',
  'Otros',
  2004,
  'Ufotable',
  'Protagonista',
  'Femenino',
  'Otro',
  'Personaje de Fate/stay night.',
  '/images/saber.png',
  'Joven',
  'Joven',
  true
),
(
  'rin_tohsaka',
  'Rin Tohsaka',
  'Fate/stay night',
  'Otros',
  2004,
  'Ufotable',
  'Deuteragonista',
  'Femenino',
  'Humano',
  'Personaje de Fate/stay night.',
  '/images/rin_tohsaka.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'archer',
  'Archer',
  'Fate/stay night',
  'Otros',
  2004,
  'Ufotable',
  'Secundario',
  'Masculino',
  'Otro',
  'Personaje de Fate/stay night.',
  '/images/archer.png',
  'Adulto',
  'Adulto',
  true
),
(
  'gintoki_sakata',
  'Gintoki Sakata',
  'Gintama',
  'Shonen',
  2003,
  'Sunrise',
  'Protagonista',
  'Masculino',
  'Humano',
  'Personaje de Gintama.',
  '/images/gintoki_sakata.png',
  'Adulto',
  'Adulto',
  true
),
(
  'kagura',
  'Kagura',
  'Gintama',
  'Shonen',
  2003,
  'Sunrise',
  'Deuteragonista',
  'Femenino',
  'Otro',
  'Personaje de Gintama.',
  '/images/kagura.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'shinpachi_shimura',
  'Shinpachi Shimura',
  'Gintama',
  'Shonen',
  2003,
  'Sunrise',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Gintama.',
  '/images/shinpachi_shimura.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'arataka_reigen',
  'Arataka Reigen',
  'Mob Psycho 100',
  'Otros',
  2012,
  'Bones',
  'Deuteragonista',
  'Masculino',
  'Humano',
  'Personaje de Mob Psycho 100.',
  '/images/arataka_reigen.png',
  'Adulto',
  'Adulto',
  true
),
(
  'anya_forger',
  'Anya Forger',
  'Spy x Family',
  'Otros',
  2019,
  'Wit Studio / CloverWorks',
  'Protagonista',
  'Femenino',
  'Humano',
  'Personaje de Spy x Family.',
  '/images/anya_forger.png',
  'Niño',
  'Niño',
  true
),
(
  'yor_forger',
  'Yor Forger',
  'Spy x Family',
  'Otros',
  2019,
  'Wit Studio / CloverWorks',
  'Deuteragonista',
  'Femenino',
  'Humano',
  'Personaje de Spy x Family.',
  '/images/yor_forger.png',
  'Adulto',
  'Adulto',
  true
),
(
  'denji',
  'Denji',
  'Chainsaw Man',
  'Shonen',
  2018,
  'MAPPA',
  'Protagonista',
  'Masculino',
  'Humano',
  'Personaje de Chainsaw Man.',
  '/images/denji.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'power',
  'Power',
  'Chainsaw Man',
  'Shonen',
  2018,
  'MAPPA',
  'Deuteragonista',
  'Femenino',
  'Demonio',
  'Personaje de Chainsaw Man.',
  '/images/power.png',
  'Adulto',
  'Adulto',
  true
),
(
  'makima',
  'Makima',
  'Chainsaw Man',
  'Shonen',
  2018,
  'MAPPA',
  'Antagonista',
  'Femenino',
  'Demonio',
  'Personaje de Chainsaw Man.',
  '/images/makima.png',
  'Adulto',
  'Adulto',
  true
),
(
  'aki_hayakawa',
  'Aki Hayakawa',
  'Chainsaw Man',
  'Shonen',
  2018,
  'MAPPA',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Chainsaw Man.',
  '/images/aki_hayakawa.png',
  'Joven',
  'Joven',
  true
),
(
  'ash_ketchum',
  'Ash Ketchum',
  'Pokemon',
  'Otros',
  1997,
  'OLM',
  'Protagonista',
  'Masculino',
  'Humano',
  'Personaje de Pokemon.',
  '/images/ash_ketchum.svg',
  'Niño',
  'Niño',
  true
),
(
  'pikachu',
  'Pikachu',
  'Pokemon',
  'Otros',
  1997,
  'OLM',
  'Deuteragonista',
  'Otro',
  'Otro',
  'Personaje de Pokemon.',
  '/images/pikachu.svg',
  'Niño',
  'Niño',
  true
),
(
  'misty',
  'Misty',
  'Pokemon',
  'Otros',
  1997,
  'OLM',
  'Secundario',
  'Femenino',
  'Humano',
  'Personaje de Pokemon.',
  '/images/misty.svg',
  'Adolescente',
  'Adolescente',
  true
),
(
  'brock',
  'Brock',
  'Pokemon',
  'Otros',
  1997,
  'OLM',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Pokemon.',
  '/images/brock.png',
  'Joven',
  'Joven',
  true
),
(
  'jessie',
  'Jessie',
  'Pokemon',
  'Otros',
  1997,
  'OLM',
  'Antagonista',
  'Femenino',
  'Humano',
  'Personaje de Pokemon.',
  '/images/jessie.png',
  'Adulto',
  'Adulto',
  true
),
(
  'james',
  'James',
  'Pokemon',
  'Otros',
  1997,
  'OLM',
  'Antagonista',
  'Masculino',
  'Humano',
  'Personaje de Pokemon.',
  '/images/james.png',
  'Adulto',
  'Adulto',
  true
),
(
  'meowth',
  'Meowth',
  'Pokemon',
  'Otros',
  1997,
  'OLM',
  'Antagonista',
  'Masculino',
  'Otro',
  'Personaje de Pokemon.',
  '/images/meowth.svg',
  'Niño',
  'Niño',
  true
),
(
  'giovanni',
  'Giovanni',
  'Pokemon',
  'Otros',
  1997,
  'OLM',
  'Antagonista',
  'Masculino',
  'Humano',
  'Personaje de Pokemon.',
  '/images/giovanni.png',
  'Adulto',
  'Adulto',
  true
),
(
  'seiya',
  'Seiya',
  'Saint Seiya',
  'Shonen',
  1986,
  'Toei Animation',
  'Protagonista',
  'Masculino',
  'Humano',
  'Personaje de Saint Seiya.',
  '/images/seiya.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'shiryu',
  'Shiryu',
  'Saint Seiya',
  'Shonen',
  1986,
  'Toei Animation',
  'Deuteragonista',
  'Masculino',
  'Humano',
  'Personaje de Saint Seiya.',
  '/images/shiryu.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'hyoga',
  'Hyoga',
  'Saint Seiya',
  'Shonen',
  1986,
  'Toei Animation',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Saint Seiya.',
  '/images/hyoga.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'shun',
  'Shun',
  'Saint Seiya',
  'Shonen',
  1986,
  'Toei Animation',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Saint Seiya.',
  '/images/shun.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'ikki',
  'Ikki',
  'Saint Seiya',
  'Shonen',
  1986,
  'Toei Animation',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Saint Seiya.',
  '/images/ikki.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'athena',
  'Athena',
  'Saint Seiya',
  'Shonen',
  1986,
  'Toei Animation',
  'Secundario',
  'Femenino',
  'Dios',
  'Personaje de Saint Seiya.',
  '/images/athena.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'hades',
  'Hades',
  'Saint Seiya',
  'Shonen',
  1986,
  'Toei Animation',
  'Antagonista',
  'Masculino',
  'Dios',
  'Personaje de Saint Seiya.',
  '/images/hades.png',
  'Mayor',
  'Mayor',
  true
),
(
  'kazuma_kuwabara',
  'Kazuma Kuwabara',
  'Yu Yu Hakusho',
  'Shonen',
  1990,
  'Studio Pierrot',
  'Deuteragonista',
  'Masculino',
  'Humano',
  'Personaje de Yu Yu Hakusho.',
  '/images/kazuma_kuwabara.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'hiei',
  'Hiei',
  'Yu Yu Hakusho',
  'Shonen',
  1990,
  'Studio Pierrot',
  'Secundario',
  'Masculino',
  'Otro',
  'Personaje de Yu Yu Hakusho.',
  '/images/hiei.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'toguro',
  'Toguro',
  'Yu Yu Hakusho',
  'Shonen',
  1990,
  'Studio Pierrot',
  'Antagonista',
  'Masculino',
  'Demonio',
  'Personaje de Yu Yu Hakusho.',
  '/images/toguro.png',
  'Adulto',
  'Adulto',
  true
),
(
  'inuyasha',
  'Inuyasha',
  'Inuyasha',
  'Shonen',
  1996,
  'Sunrise',
  'Protagonista',
  'Masculino',
  'Demonio',
  'Personaje de Inuyasha.',
  '/images/inuyasha.png',
  'Adolescente',
  'Adulto',
  true
),
(
  'kagome_higurashi',
  'Kagome Higurashi',
  'Inuyasha',
  'Shonen',
  1996,
  'Sunrise',
  'Deuteragonista',
  'Femenino',
  'Humano',
  'Personaje de Inuyasha.',
  '/images/kagome_higurashi.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'sesshomaru',
  'Sesshomaru',
  'Inuyasha',
  'Shonen',
  1996,
  'Sunrise',
  'Secundario',
  'Masculino',
  'Demonio',
  'Personaje de Inuyasha.',
  '/images/sesshomaru.png',
  'Adulto',
  'Adulto',
  true
),
(
  'naraku',
  'Naraku',
  'Inuyasha',
  'Shonen',
  1996,
  'Sunrise',
  'Antagonista',
  'Masculino',
  'Demonio',
  'Personaje de Inuyasha.',
  '/images/naraku.png',
  'Adulto',
  'Adulto',
  true
),
(
  'shippo',
  'Shippo',
  'Inuyasha',
  'Shonen',
  1996,
  'Sunrise',
  'Secundario',
  'Masculino',
  'Otro',
  'Personaje de Inuyasha.',
  '/images/shippo.png',
  'Niño',
  'Niño',
  true
),
(
  'kenshin_himura',
  'Kenshin Himura',
  'Rurouni Kenshin',
  'Shonen',
  1994,
  'Studio Gallop',
  'Protagonista',
  'Masculino',
  'Humano',
  'Personaje de Rurouni Kenshin.',
  '/images/kenshin_himura.png',
  'Adulto',
  'Adulto',
  true
),
(
  'kaoru_kamiya',
  'Kaoru Kamiya',
  'Rurouni Kenshin',
  'Shonen',
  1994,
  'Studio Gallop',
  'Deuteragonista',
  'Femenino',
  'Humano',
  'Personaje de Rurouni Kenshin.',
  '/images/kaoru_kamiya.png',
  'Joven',
  'Joven',
  true
),
(
  'makoto_shishio',
  'Makoto Shishio',
  'Rurouni Kenshin',
  'Shonen',
  1994,
  'Studio Gallop',
  'Antagonista',
  'Masculino',
  'Humano',
  'Personaje de Rurouni Kenshin.',
  '/images/makoto_shishio.png',
  'Adulto',
  'Adulto',
  true
),
(
  'sanosuke_sagara',
  'Sanosuke Sagara',
  'Rurouni Kenshin',
  'Shonen',
  1994,
  'Studio Gallop',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Rurouni Kenshin.',
  '/images/sanosuke_sagara.png',
  'Joven',
  'Joven',
  true
),
(
  'taichi_yagami',
  'Taichi Yagami',
  'Digimon Adventure',
  'Otros',
  1999,
  'Toei Animation',
  'Protagonista',
  'Masculino',
  'Humano',
  'Personaje de Digimon Adventure.',
  '/images/taichi_yagami.png',
  'Niño',
  'Niño',
  true
),
(
  'agumon',
  'Agumon',
  'Digimon Adventure',
  'Otros',
  1999,
  'Toei Animation',
  'Deuteragonista',
  'Masculino',
  'Otro',
  'Personaje de Digimon Adventure.',
  '/images/agumon.png',
  'Niño',
  'Niño',
  true
),
(
  'yamato_ishida',
  'Yamato Ishida',
  'Digimon Adventure',
  'Otros',
  1999,
  'Toei Animation',
  'Secundario',
  'Masculino',
  'Humano',
  'Personaje de Digimon Adventure.',
  '/images/yamato_ishida.png',
  'Niño',
  'Niño',
  true
),
(
  'gabumon',
  'Gabumon',
  'Digimon Adventure',
  'Otros',
  1999,
  'Toei Animation',
  'Secundario',
  'Masculino',
  'Otro',
  'Personaje de Digimon Adventure.',
  '/images/gabumon.png',
  'Niño',
  'Niño',
  true
),
(
  'sora_takenouchi',
  'Sora Takenouchi',
  'Digimon Adventure',
  'Otros',
  1999,
  'Toei Animation',
  'Secundario',
  'Femenino',
  'Humano',
  'Personaje de Digimon Adventure.',
  '/images/sora_takenouchi.png',
  'Niño',
  'Niño',
  true
),
(
  'sakura_kinomoto',
  'Sakura Kinomoto',
  'Cardcaptor Sakura',
  'Romance',
  1996,
  'Madhouse',
  'Protagonista',
  'Femenino',
  'Humano',
  'Personaje de Cardcaptor Sakura.',
  '/images/sakura_kinomoto.png',
  'Niño',
  'Niño',
  true
),
(
  'kero',
  'Kero',
  'Cardcaptor Sakura',
  'Romance',
  1996,
  'Madhouse',
  'Secundario',
  'Otro',
  'Otro',
  'Personaje de Cardcaptor Sakura.',
  '/images/kero.png',
  'Niño',
  'Niño',
  true
),
(
  'tomoyo_daidouji',
  'Tomoyo Daidouji',
  'Cardcaptor Sakura',
  'Romance',
  1996,
  'Madhouse',
  'Secundario',
  'Femenino',
  'Humano',
  'Personaje de Cardcaptor Sakura.',
  '/images/tomoyo_daidouji.png',
  'Niño',
  'Niño',
  true
),
(
  'kousei_arima',
  'Kousei Arima',
  'Your Lie in April',
  'Romance',
  2011,
  'A-1 Pictures',
  'Protagonista',
  'Masculino',
  'Humano',
  'Personaje de Your Lie in April.',
  '/images/kousei_arima.png',
  'Adolescente',
  'Adolescente',
  true
),
(
  'kaori_miyazono',
  'Kaori Miyazono',
  'Your Lie in April',
  'Romance',
  2011,
  'A-1 Pictures',
  'Deuteragonista',
  'Femenino',
  'Humano',
  'Personaje de Your Lie in April.',
  '/images/kaori_miyazono.png',
  'Adolescente',
  'Adolescente',
  true
)
on conflict (id) do update set
  name = excluded.name,
  anime = excluded.anime,
  genre = excluded.genre,
  debut_year = excluded.debut_year,
  studio = excluded.studio,
  role = excluded.role,
  gender = excluded.gender,
  race = excluded.race,
  debut_info = excluded.debut_info,
  image_url = excluded.image_url,
  age_debut_group = excluded.age_debut_group,
  age_main_group = excluded.age_main_group,
  active = excluded.active,
  updated_at = timezone('utc', now());
