export type Character = {
  id: string
  name: string
  anime: string
  genre: string
  debutYear: number
  studio: string
  role: string
  gender: string
  race: string
  debutInfo: string
  imageUrl: string
  ageDebutGroup: string
  ageMainGroup: string
  active?: boolean
}

export const CHARACTERS: Character[] = [
  {
    id: `goku`,
    name: `Goku`,
    anime: `Dragon Ball`,
    genre: `Shonen`,
    debutYear: 1984,
    studio: `Toei Animation`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Saiyajin`,
    debutInfo: `Aparece por primera vez en el capítulo 1 del manga de Dragon Ball.`,
    imageUrl: `/images/goku.png`,
    ageDebutGroup: `Niño`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `vegeta`,
    name: `Vegeta`,
    anime: `Dragon Ball`,
    genre: `Shonen`,
    debutYear: 1988,
    studio: `Toei Animation`,
    role: `Deuteragonista`,
    gender: `Masculino`,
    race: `Saiyajin`,
    debutInfo: `Príncipe de los saiyajin, aparece como rival y enemigo de Goku antes de unirse a los Guerreros Z.`,
    imageUrl: `/images/vegeta.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `naruto`,
    name: `Naruto`,
    anime: `Naruto`,
    genre: `Shonen`,
    debutYear: 1999,
    studio: `Studio Pierrot`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Debuta en el capítulo 1 del manga, como el ninja problemático de la aldea.`,
    imageUrl: `/images/naruto.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `luffy`,
    name: `Luffy`,
    anime: `One Piece`,
    genre: `Shonen`,
    debutYear: 1997,
    studio: `Toei Animation`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Lo vemos por primera vez en el capítulo 1 del manga, dentro de un barril.`,
    imageUrl: `/images/luffy.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `ichigo`,
    name: `Ichigo`,
    anime: `Bleach`,
    genre: `Shonen`,
    debutYear: 2001,
    studio: `Studio Pierrot`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Ichigo Kurosaki debuta como un estudiante que puede ver espíritus y obtiene poderes de shinigami.`,
    imageUrl: `/images/ichigo.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `edward_elric`,
    name: `Edward Elric`,
    anime: `Fullmetal Alchemist`,
    genre: `Shonen`,
    debutYear: 2001,
    studio: `Bones`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `El joven alquimista estatal que busca recuperar el cuerpo de su hermano tras un fallo en una transmutación prohibida.`,
    imageUrl: `/images/edward_elric.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `tanjiro`,
    name: `Tanjiro`,
    anime: `Kimetsu no Yaiba`,
    genre: `Shonen`,
    debutYear: 2016,
    studio: `Ufotable`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Tanjiro Kamado debuta como un chico que pierde a su familia y decide convertirse en cazador de demonios.`,
    imageUrl: `/images/tanjiro.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `deku`,
    name: `Deku`,
    anime: `My Hero Academia`,
    genre: `Shonen`,
    debutYear: 2014,
    studio: `Bones`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Izuku Midoriya, un chico sin poderes en un mundo de héroes, hereda el One For All.`,
    imageUrl: `/images/deku.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `light_yagami`,
    name: `Light Yagami`,
    anime: `Death Note`,
    genre: `Otros`,
    debutYear: 2003,
    studio: `Madhouse`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Estudiante ejemplar que encuentra un cuaderno con el poder de matar a quien tenga su nombre escrito.`,
    imageUrl: `/images/light_yagami.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `lelouch`,
    name: `Lelouch`,
    anime: `Code Geass`,
    genre: `Otros`,
    debutYear: 2006,
    studio: `Sunrise`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Príncipe exiliado que obtiene el poder del Geass y lidera una rebelión usando el alias Zero.`,
    imageUrl: `/images/lelouch.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `spike`,
    name: `Spike Spiegel`,
    anime: `Cowboy Bebop`,
    genre: `Otros`,
    debutYear: 1998,
    studio: `Sunrise`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Cazarrecompensas relajado y letal, con un pasado oscuro ligado al sindicato criminal.`,
    imageUrl: `/images/spike.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `sakuragi`,
    name: `Sakuragi`,
    anime: `Slam Dunk`,
    genre: `Deportes`,
    debutYear: 1990,
    studio: `Toei Animation`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Hanamichi Sakuragi aparece en el capítulo 1, rechazado por una chica y metido en peleas.`,
    imageUrl: `/images/sakuragi.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `rukawa`,
    name: `Rukawa`,
    anime: `Slam Dunk`,
    genre: `Deportes`,
    debutYear: 1990,
    studio: `Toei Animation`,
    role: `Deuteragonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Kaede Rukawa es el talentoso rival de Sakuragi en el Shohoku, frío y centrado en el básquetbol.`,
    imageUrl: `/images/rukawa.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `hinata`,
    name: `Hinata`,
    anime: `Haikyuu!!`,
    genre: `Deportes`,
    debutYear: 2012,
    studio: `Production I.G`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Shoyo Hinata debuta como el pequeño atacante apasionado por el vóleibol.`,
    imageUrl: `/images/hinata.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `kageyama`,
    name: `Kageyama`,
    anime: `Haikyuu!!`,
    genre: `Deportes`,
    debutYear: 2012,
    studio: `Production I.G`,
    role: `Deuteragonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Tobio Kageyama es el talentoso colocador apodado el “Rey de la cancha”.`,
    imageUrl: `/images/kageyama.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `taiga`,
    name: `Taiga`,
    anime: `Toradora!`,
    genre: `Romance`,
    debutYear: 2006,
    studio: `J.C.Staff`,
    role: `Protagonista`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Taiga Aisaka aparece como la “Tigre de Bolsillo”, conocida por su mal carácter.`,
    imageUrl: `/images/taiga.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `kaguya`,
    name: `Kaguya`,
    anime: `Kaguya-sama: Love is War`,
    genre: `Romance`,
    debutYear: 2015,
    studio: `A-1 Pictures`,
    role: `Protagonista`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Kaguya Shinomiya es la vicepresidenta del consejo estudiantil que compite en juegos mentales de amor con Shirogane.`,
    imageUrl: `/images/kaguya.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `usagi`,
    name: `Usagi`,
    anime: `Sailor Moon`,
    genre: `Otros`,
    debutYear: 1991,
    studio: `Toei Animation`,
    role: `Protagonista`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Usagi Tsukino debuta como una estudiante torpe que descubre que es Sailor Moon.`,
    imageUrl: `/images/usagi.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `zero_two`,
    name: `Zero Two`,
    anime: `Darling in the Franxx`,
    genre: `Otros`,
    debutYear: 2018,
    studio: `Trigger / A-1 Pictures`,
    role: `Deuteragonista`,
    gender: `Femenino`,
    race: `Otro`,
    debutInfo: `Piloto misteriosa con cuernos rojos, conocida como el “monstruo” que nadie quiere como pareja… hasta Hiro.`,
    imageUrl: `/images/zero_two.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `gohan`,
    name: `Gohan`,
    anime: `Dragon Ball`,
    genre: `Shonen`,
    debutYear: 1988,
    studio: `Toei Animation`,
    role: `Deuteragonista`,
    gender: `Masculino`,
    race: `Saiyajin`,
    debutInfo: `Personaje de Dragon Ball.`,
    imageUrl: `/images/gohan.png`,
    ageDebutGroup: `Niño`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `piccolo`,
    name: `Piccolo`,
    anime: `Dragon Ball`,
    genre: `Shonen`,
    debutYear: 1984,
    studio: `Toei Animation`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Otro`,
    debutInfo: `Personaje de Dragon Ball.`,
    imageUrl: `/images/piccolo.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `freezer`,
    name: `Freezer`,
    anime: `Dragon Ball`,
    genre: `Shonen`,
    debutYear: 1984,
    studio: `Toei Animation`,
    role: `Antagonista`,
    gender: `Otro`,
    race: `Alien`,
    debutInfo: `Personaje de Dragon Ball.`,
    imageUrl: `/images/freezer.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `cell`,
    name: `Cell`,
    anime: `Dragon Ball`,
    genre: `Shonen`,
    debutYear: 1984,
    studio: `Toei Animation`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Androide`,
    debutInfo: `Personaje de Dragon Ball.`,
    imageUrl: `/images/cell.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `trunks`,
    name: `Trunks`,
    anime: `Dragon Ball`,
    genre: `Shonen`,
    debutYear: 1984,
    studio: `Toei Animation`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Saiyajin`,
    debutInfo: `Personaje de Dragon Ball.`,
    imageUrl: `/images/trunks.png`,
    ageDebutGroup: `Joven`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `bulma`,
    name: `Bulma`,
    anime: `Dragon Ball`,
    genre: `Shonen`,
    debutYear: 1984,
    studio: `Toei Animation`,
    role: `Secundario`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de Dragon Ball.`,
    imageUrl: `/images/bulma.png`,
    ageDebutGroup: `Joven`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `krillin`,
    name: `Krillin`,
    anime: `Dragon Ball`,
    genre: `Shonen`,
    debutYear: 1984,
    studio: `Toei Animation`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Dragon Ball.`,
    imageUrl: `/images/krillin.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `majin_buu`,
    name: `Majin Buu`,
    anime: `Dragon Ball`,
    genre: `Shonen`,
    debutYear: 1984,
    studio: `Toei Animation`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Demonio`,
    debutInfo: `Personaje de Dragon Ball.`,
    imageUrl: `/images/majin_buu.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `beerus`,
    name: `Beerus`,
    anime: `Dragon Ball`,
    genre: `Shonen`,
    debutYear: 1984,
    studio: `Toei Animation`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Dios`,
    debutInfo: `Personaje de Dragon Ball.`,
    imageUrl: `/images/beerus.png`,
    ageDebutGroup: `Mayor`,
    ageMainGroup: `Mayor`,
    active: true,
  },
  {
    id: `whis`,
    name: `Whis`,
    anime: `Dragon Ball`,
    genre: `Shonen`,
    debutYear: 1984,
    studio: `Toei Animation`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Angel`,
    debutInfo: `Personaje de Dragon Ball.`,
    imageUrl: `/images/whis.png`,
    ageDebutGroup: `Mayor`,
    ageMainGroup: `Mayor`,
    active: true,
  },
  {
    id: `roronoa_zoro`,
    name: `Roronoa Zoro`,
    anime: `One Piece`,
    genre: `Shonen`,
    debutYear: 1997,
    studio: `Toei Animation`,
    role: `Deuteragonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de One Piece.`,
    imageUrl: `/images/roronoa_zoro.png`,
    ageDebutGroup: `Joven`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `nami`,
    name: `Nami`,
    anime: `One Piece`,
    genre: `Shonen`,
    debutYear: 1997,
    studio: `Toei Animation`,
    role: `Secundario`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de One Piece.`,
    imageUrl: `/images/nami.png`,
    ageDebutGroup: `Joven`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `sanji`,
    name: `Sanji`,
    anime: `One Piece`,
    genre: `Shonen`,
    debutYear: 1997,
    studio: `Toei Animation`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de One Piece.`,
    imageUrl: `/images/sanji.png`,
    ageDebutGroup: `Joven`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `usopp`,
    name: `Usopp`,
    anime: `One Piece`,
    genre: `Shonen`,
    debutYear: 1997,
    studio: `Toei Animation`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de One Piece.`,
    imageUrl: `/images/usopp.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `tony_tony_chopper`,
    name: `Tony Tony Chopper`,
    anime: `One Piece`,
    genre: `Shonen`,
    debutYear: 1997,
    studio: `Toei Animation`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Otro`,
    debutInfo: `Personaje de One Piece.`,
    imageUrl: `/images/tony_tony_chopper.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `nico_robin`,
    name: `Nico Robin`,
    anime: `One Piece`,
    genre: `Shonen`,
    debutYear: 1997,
    studio: `Toei Animation`,
    role: `Secundario`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de One Piece.`,
    imageUrl: `/images/nico_robin.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `franky`,
    name: `Franky`,
    anime: `One Piece`,
    genre: `Shonen`,
    debutYear: 1997,
    studio: `Toei Animation`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Cyborg`,
    debutInfo: `Personaje de One Piece.`,
    imageUrl: `/images/franky.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `brook`,
    name: `Brook`,
    anime: `One Piece`,
    genre: `Shonen`,
    debutYear: 1997,
    studio: `Toei Animation`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Otro`,
    debutInfo: `Personaje de One Piece.`,
    imageUrl: `/images/brook.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `jinbe`,
    name: `Jinbe`,
    anime: `One Piece`,
    genre: `Shonen`,
    debutYear: 1997,
    studio: `Toei Animation`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Otro`,
    debutInfo: `Personaje de One Piece.`,
    imageUrl: `/images/jinbe.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `portgas_d_ace`,
    name: `Portgas D. Ace`,
    anime: `One Piece`,
    genre: `Shonen`,
    debutYear: 1997,
    studio: `Toei Animation`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de One Piece.`,
    imageUrl: `/images/portgas_d_ace.png`,
    ageDebutGroup: `Joven`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `trafalgar_law`,
    name: `Trafalgar Law`,
    anime: `One Piece`,
    genre: `Shonen`,
    debutYear: 1997,
    studio: `Toei Animation`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de One Piece.`,
    imageUrl: `/images/trafalgar_law.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `shanks`,
    name: `Shanks`,
    anime: `One Piece`,
    genre: `Shonen`,
    debutYear: 1997,
    studio: `Toei Animation`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de One Piece.`,
    imageUrl: `/images/shanks.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `marshall_d_teach`,
    name: `Marshall D. Teach`,
    anime: `One Piece`,
    genre: `Shonen`,
    debutYear: 1997,
    studio: `Toei Animation`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de One Piece.`,
    imageUrl: `/images/marshall_d_teach.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `boa_hancock`,
    name: `Boa Hancock`,
    anime: `One Piece`,
    genre: `Shonen`,
    debutYear: 1997,
    studio: `Toei Animation`,
    role: `Secundario`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de One Piece.`,
    imageUrl: `/images/boa_hancock.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `sabo`,
    name: `Sabo`,
    anime: `One Piece`,
    genre: `Shonen`,
    debutYear: 1997,
    studio: `Toei Animation`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de One Piece.`,
    imageUrl: `/images/sabo.png`,
    ageDebutGroup: `Joven`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `donquixote_doflamingo`,
    name: `Donquixote Doflamingo`,
    anime: `One Piece`,
    genre: `Shonen`,
    debutYear: 1997,
    studio: `Toei Animation`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de One Piece.`,
    imageUrl: `/images/donquixote_doflamingo.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `kaido`,
    name: `Kaido`,
    anime: `One Piece`,
    genre: `Shonen`,
    debutYear: 1997,
    studio: `Toei Animation`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Otro`,
    debutInfo: `Personaje de One Piece.`,
    imageUrl: `/images/kaido.png`,
    ageDebutGroup: `Mayor`,
    ageMainGroup: `Mayor`,
    active: true,
  },
  {
    id: `big_mom`,
    name: `Big Mom`,
    anime: `One Piece`,
    genre: `Shonen`,
    debutYear: 1997,
    studio: `Toei Animation`,
    role: `Antagonista`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de One Piece.`,
    imageUrl: `/images/big_mom.png`,
    ageDebutGroup: `Mayor`,
    ageMainGroup: `Mayor`,
    active: true,
  },
  {
    id: `sasuke_uchiha`,
    name: `Sasuke Uchiha`,
    anime: `Naruto`,
    genre: `Shonen`,
    debutYear: 1999,
    studio: `Studio Pierrot`,
    role: `Deuteragonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Naruto.`,
    imageUrl: `/images/sasuke_uchiha.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `sakura_haruno`,
    name: `Sakura Haruno`,
    anime: `Naruto`,
    genre: `Shonen`,
    debutYear: 1999,
    studio: `Studio Pierrot`,
    role: `Secundario`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de Naruto.`,
    imageUrl: `/images/sakura_haruno.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `kakashi_hatake`,
    name: `Kakashi Hatake`,
    anime: `Naruto`,
    genre: `Shonen`,
    debutYear: 1999,
    studio: `Studio Pierrot`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Naruto.`,
    imageUrl: `/images/kakashi_hatake.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `itachi_uchiha`,
    name: `Itachi Uchiha`,
    anime: `Naruto`,
    genre: `Shonen`,
    debutYear: 1999,
    studio: `Studio Pierrot`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Naruto.`,
    imageUrl: `/images/itachi_uchiha.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `gaara`,
    name: `Gaara`,
    anime: `Naruto`,
    genre: `Shonen`,
    debutYear: 1999,
    studio: `Studio Pierrot`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Naruto.`,
    imageUrl: `/images/gaara.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `jiraiya`,
    name: `Jiraiya`,
    anime: `Naruto`,
    genre: `Shonen`,
    debutYear: 1999,
    studio: `Studio Pierrot`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Naruto.`,
    imageUrl: `/images/jiraiya.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Mayor`,
    active: true,
  },
  {
    id: `orochimaru`,
    name: `Orochimaru`,
    anime: `Naruto`,
    genre: `Shonen`,
    debutYear: 1999,
    studio: `Studio Pierrot`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Naruto.`,
    imageUrl: `/images/orochimaru.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Mayor`,
    active: true,
  },
  {
    id: `pain`,
    name: `Pain`,
    anime: `Naruto`,
    genre: `Shonen`,
    debutYear: 1999,
    studio: `Studio Pierrot`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Naruto.`,
    imageUrl: `/images/pain.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `madara_uchiha`,
    name: `Madara Uchiha`,
    anime: `Naruto`,
    genre: `Shonen`,
    debutYear: 1999,
    studio: `Studio Pierrot`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Naruto.`,
    imageUrl: `/images/madara_uchiha.png`,
    ageDebutGroup: `Mayor`,
    ageMainGroup: `Mayor`,
    active: true,
  },
  {
    id: `obito_uchiha`,
    name: `Obito Uchiha`,
    anime: `Naruto`,
    genre: `Shonen`,
    debutYear: 1999,
    studio: `Studio Pierrot`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Naruto.`,
    imageUrl: `/images/obito_uchiha.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `tsunade`,
    name: `Tsunade`,
    anime: `Naruto`,
    genre: `Shonen`,
    debutYear: 1999,
    studio: `Studio Pierrot`,
    role: `Secundario`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de Naruto.`,
    imageUrl: `/images/tsunade.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Mayor`,
    active: true,
  },
  {
    id: `shikamaru_nara`,
    name: `Shikamaru Nara`,
    anime: `Naruto`,
    genre: `Shonen`,
    debutYear: 1999,
    studio: `Studio Pierrot`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Naruto.`,
    imageUrl: `/images/shikamaru_nara.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `rukia_kuchiki`,
    name: `Rukia Kuchiki`,
    anime: `Bleach`,
    genre: `Shonen`,
    debutYear: 2001,
    studio: `Studio Pierrot`,
    role: `Deuteragonista`,
    gender: `Femenino`,
    race: `Shinigami`,
    debutInfo: `Personaje de Bleach.`,
    imageUrl: `/images/rukia_kuchiki.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `sosuke_aizen`,
    name: `Sosuke Aizen`,
    anime: `Bleach`,
    genre: `Shonen`,
    debutYear: 2001,
    studio: `Studio Pierrot`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Shinigami`,
    debutInfo: `Personaje de Bleach.`,
    imageUrl: `/images/sosuke_aizen.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `renji_abarai`,
    name: `Renji Abarai`,
    anime: `Bleach`,
    genre: `Shonen`,
    debutYear: 2001,
    studio: `Studio Pierrot`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Shinigami`,
    debutInfo: `Personaje de Bleach.`,
    imageUrl: `/images/renji_abarai.png`,
    ageDebutGroup: `Joven`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `byakuya_kuchiki`,
    name: `Byakuya Kuchiki`,
    anime: `Bleach`,
    genre: `Shonen`,
    debutYear: 2001,
    studio: `Studio Pierrot`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Shinigami`,
    debutInfo: `Personaje de Bleach.`,
    imageUrl: `/images/byakuya_kuchiki.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `orihime_inoue`,
    name: `Orihime Inoue`,
    anime: `Bleach`,
    genre: `Shonen`,
    debutYear: 2001,
    studio: `Studio Pierrot`,
    role: `Secundario`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de Bleach.`,
    imageUrl: `/images/orihime_inoue.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `uryu_ishida`,
    name: `Uryu Ishida`,
    anime: `Bleach`,
    genre: `Shonen`,
    debutYear: 2001,
    studio: `Studio Pierrot`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Bleach.`,
    imageUrl: `/images/uryu_ishida.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `kenpachi_zaraki`,
    name: `Kenpachi Zaraki`,
    anime: `Bleach`,
    genre: `Shonen`,
    debutYear: 2001,
    studio: `Studio Pierrot`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Shinigami`,
    debutInfo: `Personaje de Bleach.`,
    imageUrl: `/images/kenpachi_zaraki.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `toshiro_hitsugaya`,
    name: `Toshiro Hitsugaya`,
    anime: `Bleach`,
    genre: `Shonen`,
    debutYear: 2001,
    studio: `Studio Pierrot`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Shinigami`,
    debutInfo: `Personaje de Bleach.`,
    imageUrl: `/images/toshiro_hitsugaya.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `yoruichi_shihoin`,
    name: `Yoruichi Shihoin`,
    anime: `Bleach`,
    genre: `Shonen`,
    debutYear: 2001,
    studio: `Studio Pierrot`,
    role: `Secundario`,
    gender: `Femenino`,
    race: `Shinigami`,
    debutInfo: `Personaje de Bleach.`,
    imageUrl: `/images/yoruichi_shihoin.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `nezuko_kamado`,
    name: `Nezuko Kamado`,
    anime: `Kimetsu no Yaiba`,
    genre: `Shonen`,
    debutYear: 2016,
    studio: `Ufotable`,
    role: `Deuteragonista`,
    gender: `Femenino`,
    race: `Demonio`,
    debutInfo: `Personaje de Kimetsu no Yaiba.`,
    imageUrl: `/images/nezuko_kamado.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `zenitsu_agatsuma`,
    name: `Zenitsu Agatsuma`,
    anime: `Kimetsu no Yaiba`,
    genre: `Shonen`,
    debutYear: 2016,
    studio: `Ufotable`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Kimetsu no Yaiba.`,
    imageUrl: `/images/zenitsu_agatsuma.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `inosuke_hashibira`,
    name: `Inosuke Hashibira`,
    anime: `Kimetsu no Yaiba`,
    genre: `Shonen`,
    debutYear: 2016,
    studio: `Ufotable`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Kimetsu no Yaiba.`,
    imageUrl: `/images/inosuke_hashibira.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `giyu_tomioka`,
    name: `Giyu Tomioka`,
    anime: `Kimetsu no Yaiba`,
    genre: `Shonen`,
    debutYear: 2016,
    studio: `Ufotable`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Kimetsu no Yaiba.`,
    imageUrl: `/images/giyu_tomioka.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `shinobu_kocho`,
    name: `Shinobu Kocho`,
    anime: `Kimetsu no Yaiba`,
    genre: `Shonen`,
    debutYear: 2016,
    studio: `Ufotable`,
    role: `Secundario`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de Kimetsu no Yaiba.`,
    imageUrl: `/images/shinobu_kocho.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `muzan_kibutsuji`,
    name: `Muzan Kibutsuji`,
    anime: `Kimetsu no Yaiba`,
    genre: `Shonen`,
    debutYear: 2016,
    studio: `Ufotable`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Demonio`,
    debutInfo: `Personaje de Kimetsu no Yaiba.`,
    imageUrl: `/images/muzan_kibutsuji.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Mayor`,
    active: true,
  },
  {
    id: `izuku_midoriya`,
    name: `Izuku Midoriya`,
    anime: `My Hero Academia`,
    genre: `Shonen`,
    debutYear: 2014,
    studio: `Bones`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de My Hero Academia.`,
    imageUrl: `/images/izuku_midoriya.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `katsuki_bakugo`,
    name: `Katsuki Bakugo`,
    anime: `My Hero Academia`,
    genre: `Shonen`,
    debutYear: 2014,
    studio: `Bones`,
    role: `Deuteragonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de My Hero Academia.`,
    imageUrl: `/images/katsuki_bakugo.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `shoto_todoroki`,
    name: `Shoto Todoroki`,
    anime: `My Hero Academia`,
    genre: `Shonen`,
    debutYear: 2014,
    studio: `Bones`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de My Hero Academia.`,
    imageUrl: `/images/shoto_todoroki.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `all_might`,
    name: `All Might`,
    anime: `My Hero Academia`,
    genre: `Shonen`,
    debutYear: 2014,
    studio: `Bones`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de My Hero Academia.`,
    imageUrl: `/images/all_might.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Mayor`,
    active: true,
  },
  {
    id: `ochaco_uraraka`,
    name: `Ochaco Uraraka`,
    anime: `My Hero Academia`,
    genre: `Shonen`,
    debutYear: 2014,
    studio: `Bones`,
    role: `Secundario`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de My Hero Academia.`,
    imageUrl: `/images/ochaco_uraraka.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `shota_aizawa`,
    name: `Shota Aizawa`,
    anime: `My Hero Academia`,
    genre: `Shonen`,
    debutYear: 2014,
    studio: `Bones`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de My Hero Academia.`,
    imageUrl: `/images/shota_aizawa.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `tomura_shigaraki`,
    name: `Tomura Shigaraki`,
    anime: `My Hero Academia`,
    genre: `Shonen`,
    debutYear: 2014,
    studio: `Bones`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de My Hero Academia.`,
    imageUrl: `/images/tomura_shigaraki.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `dabi`,
    name: `Dabi`,
    anime: `My Hero Academia`,
    genre: `Shonen`,
    debutYear: 2014,
    studio: `Bones`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de My Hero Academia.`,
    imageUrl: `/images/dabi.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `l`,
    name: `L`,
    anime: `Death Note`,
    genre: `Shonen`,
    debutYear: 2003,
    studio: `Madhouse`,
    role: `Deuteragonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Death Note.`,
    imageUrl: `/images/l.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `ryuk`,
    name: `Ryuk`,
    anime: `Death Note`,
    genre: `Shonen`,
    debutYear: 2003,
    studio: `Madhouse`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Shinigami`,
    debutInfo: `Personaje de Death Note.`,
    imageUrl: `/images/ryuk.png`,
    ageDebutGroup: `Mayor`,
    ageMainGroup: `Mayor`,
    active: true,
  },
  {
    id: `misa_amane`,
    name: `Misa Amane`,
    anime: `Death Note`,
    genre: `Shonen`,
    debutYear: 2003,
    studio: `Madhouse`,
    role: `Secundario`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de Death Note.`,
    imageUrl: `/images/misa_amane.png`,
    ageDebutGroup: `Joven`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `near`,
    name: `Near`,
    anime: `Death Note`,
    genre: `Shonen`,
    debutYear: 2003,
    studio: `Madhouse`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Death Note.`,
    imageUrl: `/images/near.png`,
    ageDebutGroup: `Niño`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `suzaku_kururugi`,
    name: `Suzaku Kururugi`,
    anime: `Code Geass`,
    genre: `Otros`,
    debutYear: 2006,
    studio: `Sunrise`,
    role: `Deuteragonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Code Geass.`,
    imageUrl: `/images/suzaku_kururugi.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `c_c`,
    name: `C.C.`,
    anime: `Code Geass`,
    genre: `Otros`,
    debutYear: 2006,
    studio: `Sunrise`,
    role: `Secundario`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de Code Geass.`,
    imageUrl: `/images/c_c.png`,
    ageDebutGroup: `Mayor`,
    ageMainGroup: `Mayor`,
    active: true,
  },
  {
    id: `ed`,
    name: `Ed`,
    anime: `Cowboy Bebop`,
    genre: `Otros`,
    debutYear: 1998,
    studio: `Sunrise`,
    role: `Secundario`,
    gender: `Otro`,
    race: `Humano`,
    debutInfo: `Personaje de Cowboy Bebop.`,
    imageUrl: `/images/ed.png`,
    ageDebutGroup: `Niño`,
    ageMainGroup: `Niño`,
    active: true,
  },
  {
    id: `vicious`,
    name: `Vicious`,
    anime: `Cowboy Bebop`,
    genre: `Otros`,
    debutYear: 1998,
    studio: `Sunrise`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Cowboy Bebop.`,
    imageUrl: `/images/vicious.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `yuji_itadori`,
    name: `Yuji Itadori`,
    anime: `Jujutsu Kaisen`,
    genre: `Shonen`,
    debutYear: 2018,
    studio: `MAPPA`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Jujutsu Kaisen.`,
    imageUrl: `/images/yuji_itadori.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `megumi_fushiguro`,
    name: `Megumi Fushiguro`,
    anime: `Jujutsu Kaisen`,
    genre: `Shonen`,
    debutYear: 2018,
    studio: `MAPPA`,
    role: `Deuteragonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Jujutsu Kaisen.`,
    imageUrl: `/images/megumi_fushiguro.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `nobara_kugisaki`,
    name: `Nobara Kugisaki`,
    anime: `Jujutsu Kaisen`,
    genre: `Shonen`,
    debutYear: 2018,
    studio: `MAPPA`,
    role: `Secundario`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de Jujutsu Kaisen.`,
    imageUrl: `/images/nobara_kugisaki.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `satoru_gojo`,
    name: `Satoru Gojo`,
    anime: `Jujutsu Kaisen`,
    genre: `Shonen`,
    debutYear: 2018,
    studio: `MAPPA`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Jujutsu Kaisen.`,
    imageUrl: `/images/satoru_gojo.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `ryomen_sukuna`,
    name: `Ryomen Sukuna`,
    anime: `Jujutsu Kaisen`,
    genre: `Shonen`,
    debutYear: 2018,
    studio: `MAPPA`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Demonio`,
    debutInfo: `Personaje de Jujutsu Kaisen.`,
    imageUrl: `/images/ryomen_sukuna.png`,
    ageDebutGroup: `Mayor`,
    ageMainGroup: `Mayor`,
    active: true,
  },
  {
    id: `suguru_geto`,
    name: `Suguru Geto`,
    anime: `Jujutsu Kaisen`,
    genre: `Shonen`,
    debutYear: 2018,
    studio: `MAPPA`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Jujutsu Kaisen.`,
    imageUrl: `/images/suguru_geto.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `eren_yeager`,
    name: `Eren Yeager`,
    anime: `Attack on Titan`,
    genre: `Otros`,
    debutYear: 2009,
    studio: `Wit Studio / MAPPA`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Attack on Titan.`,
    imageUrl: `/images/eren_yeager.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `mikasa_ackerman`,
    name: `Mikasa Ackerman`,
    anime: `Attack on Titan`,
    genre: `Otros`,
    debutYear: 2009,
    studio: `Wit Studio / MAPPA`,
    role: `Deuteragonista`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de Attack on Titan.`,
    imageUrl: `/images/mikasa_ackerman.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `erwin_smith`,
    name: `Erwin Smith`,
    anime: `Attack on Titan`,
    genre: `Otros`,
    debutYear: 2009,
    studio: `Wit Studio / MAPPA`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Attack on Titan.`,
    imageUrl: `/images/erwin_smith.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `hange_zoe`,
    name: `Hange Zoe`,
    anime: `Attack on Titan`,
    genre: `Otros`,
    debutYear: 2009,
    studio: `Wit Studio / MAPPA`,
    role: `Secundario`,
    gender: `Otro`,
    race: `Humano`,
    debutInfo: `Personaje de Attack on Titan.`,
    imageUrl: `/images/hange_zoe.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `reiner_braun`,
    name: `Reiner Braun`,
    anime: `Attack on Titan`,
    genre: `Otros`,
    debutYear: 2009,
    studio: `Wit Studio / MAPPA`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Attack on Titan.`,
    imageUrl: `/images/reiner_braun.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `zeke_yeager`,
    name: `Zeke Yeager`,
    anime: `Attack on Titan`,
    genre: `Otros`,
    debutYear: 2009,
    studio: `Wit Studio / MAPPA`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Attack on Titan.`,
    imageUrl: `/images/zeke_yeager.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `roy_mustang`,
    name: `Roy Mustang`,
    anime: `Fullmetal Alchemist`,
    genre: `Shonen`,
    debutYear: 2001,
    studio: `Bones`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Fullmetal Alchemist.`,
    imageUrl: `/images/roy_mustang.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `scar`,
    name: `Scar`,
    anime: `Fullmetal Alchemist`,
    genre: `Shonen`,
    debutYear: 2001,
    studio: `Bones`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Fullmetal Alchemist.`,
    imageUrl: `/images/scar.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `gon_freecss`,
    name: `Gon Freecss`,
    anime: `Hunter x Hunter`,
    genre: `Shonen`,
    debutYear: 1998,
    studio: `Madhouse`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Hunter x Hunter.`,
    imageUrl: `/images/gon_freecss.png`,
    ageDebutGroup: `Niño`,
    ageMainGroup: `Niño`,
    active: true,
  },
  {
    id: `kurapika`,
    name: `Kurapika`,
    anime: `Hunter x Hunter`,
    genre: `Shonen`,
    debutYear: 1998,
    studio: `Madhouse`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Hunter x Hunter.`,
    imageUrl: `/images/kurapika.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `hisoka`,
    name: `Hisoka`,
    anime: `Hunter x Hunter`,
    genre: `Shonen`,
    debutYear: 1998,
    studio: `Madhouse`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Hunter x Hunter.`,
    imageUrl: `/images/hisoka.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `meruem`,
    name: `Meruem`,
    anime: `Hunter x Hunter`,
    genre: `Shonen`,
    debutYear: 1998,
    studio: `Madhouse`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Otro`,
    debutInfo: `Personaje de Hunter x Hunter.`,
    imageUrl: `/images/meruem.png`,
    ageDebutGroup: `Mayor`,
    ageMainGroup: `Mayor`,
    active: true,
  },
  {
    id: `isaac_netero`,
    name: `Isaac Netero`,
    anime: `Hunter x Hunter`,
    genre: `Shonen`,
    debutYear: 1998,
    studio: `Madhouse`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Hunter x Hunter.`,
    imageUrl: `/images/isaac_netero.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Mayor`,
    active: true,
  },
  {
    id: `jonathan_joestar`,
    name: `Jonathan Joestar`,
    anime: `JoJo's Bizarre Adventure`,
    genre: `Shonen`,
    debutYear: 1987,
    studio: `David Production`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de JoJo's Bizarre Adventure.`,
    imageUrl: `/images/jonathan_joestar.png`,
    ageDebutGroup: `Joven`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `joseph_joestar`,
    name: `Joseph Joestar`,
    anime: `JoJo's Bizarre Adventure`,
    genre: `Shonen`,
    debutYear: 1987,
    studio: `David Production`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de JoJo's Bizarre Adventure.`,
    imageUrl: `/images/joseph_joestar.png`,
    ageDebutGroup: `Joven`,
    ageMainGroup: `Mayor`,
    active: true,
  },
  {
    id: `jotaro_kujo`,
    name: `Jotaro Kujo`,
    anime: `JoJo's Bizarre Adventure`,
    genre: `Shonen`,
    debutYear: 1987,
    studio: `David Production`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de JoJo's Bizarre Adventure.`,
    imageUrl: `/images/jotaro_kujo.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `dio_brando`,
    name: `Dio Brando`,
    anime: `JoJo's Bizarre Adventure`,
    genre: `Shonen`,
    debutYear: 1987,
    studio: `David Production`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Otro`,
    debutInfo: `Personaje de JoJo's Bizarre Adventure.`,
    imageUrl: `/images/dio_brando.png`,
    ageDebutGroup: `Mayor`,
    ageMainGroup: `Mayor`,
    active: true,
  },
  {
    id: `josuke_higashikata`,
    name: `Josuke Higashikata`,
    anime: `JoJo's Bizarre Adventure`,
    genre: `Shonen`,
    debutYear: 1987,
    studio: `David Production`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de JoJo's Bizarre Adventure.`,
    imageUrl: `/images/josuke_higashikata.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `giorno_giovanna`,
    name: `Giorno Giovanna`,
    anime: `JoJo's Bizarre Adventure`,
    genre: `Shonen`,
    debutYear: 1987,
    studio: `David Production`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de JoJo's Bizarre Adventure.`,
    imageUrl: `/images/giorno_giovanna.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `saitama`,
    name: `Saitama`,
    anime: `One Punch Man`,
    genre: `Shonen`,
    debutYear: 2009,
    studio: `Madhouse`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de One Punch Man.`,
    imageUrl: `/images/saitama.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `genos`,
    name: `Genos`,
    anime: `One Punch Man`,
    genre: `Shonen`,
    debutYear: 2009,
    studio: `Madhouse`,
    role: `Deuteragonista`,
    gender: `Masculino`,
    race: `Cyborg`,
    debutInfo: `Personaje de One Punch Man.`,
    imageUrl: `/images/genos.png`,
    ageDebutGroup: `Joven`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `tatsumaki`,
    name: `Tatsumaki`,
    anime: `One Punch Man`,
    genre: `Shonen`,
    debutYear: 2009,
    studio: `Madhouse`,
    role: `Secundario`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de One Punch Man.`,
    imageUrl: `/images/tatsumaki.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `garou`,
    name: `Garou`,
    anime: `One Punch Man`,
    genre: `Shonen`,
    debutYear: 2009,
    studio: `Madhouse`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de One Punch Man.`,
    imageUrl: `/images/garou.png`,
    ageDebutGroup: `Joven`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `king`,
    name: `King`,
    anime: `One Punch Man`,
    genre: `Shonen`,
    debutYear: 2009,
    studio: `Madhouse`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de One Punch Man.`,
    imageUrl: `/images/king.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `ken_kaneki`,
    name: `Ken Kaneki`,
    anime: `Tokyo Ghoul`,
    genre: `Otros`,
    debutYear: 2011,
    studio: `Studio Pierrot`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Ghoul`,
    debutInfo: `Personaje de Tokyo Ghoul.`,
    imageUrl: `/images/ken_kaneki.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `touka_kirishima`,
    name: `Touka Kirishima`,
    anime: `Tokyo Ghoul`,
    genre: `Otros`,
    debutYear: 2011,
    studio: `Studio Pierrot`,
    role: `Deuteragonista`,
    gender: `Femenino`,
    race: `Ghoul`,
    debutInfo: `Personaje de Tokyo Ghoul.`,
    imageUrl: `/images/touka_kirishima.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `jason`,
    name: `Jason`,
    anime: `Tokyo Ghoul`,
    genre: `Otros`,
    debutYear: 2011,
    studio: `Studio Pierrot`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Ghoul`,
    debutInfo: `Personaje de Tokyo Ghoul.`,
    imageUrl: `/images/jason.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `tooru_oikawa`,
    name: `Tooru Oikawa`,
    anime: `Haikyuu!!`,
    genre: `Deportes`,
    debutYear: 2012,
    studio: `Production I.G`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Haikyuu!!.`,
    imageUrl: `/images/tooru_oikawa.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `kenma_kozume`,
    name: `Kenma Kozume`,
    anime: `Haikyuu!!`,
    genre: `Deportes`,
    debutYear: 2012,
    studio: `Production I.G`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Haikyuu!!.`,
    imageUrl: `/images/kenma_kozume.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `kei_tsukishima`,
    name: `Kei Tsukishima`,
    anime: `Haikyuu!!`,
    genre: `Deportes`,
    debutYear: 2012,
    studio: `Production I.G`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Haikyuu!!.`,
    imageUrl: `/images/kei_tsukishima.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `takenori_akagi`,
    name: `Takenori Akagi`,
    anime: `Slam Dunk`,
    genre: `Deportes`,
    debutYear: 1990,
    studio: `Toei Animation`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Slam Dunk.`,
    imageUrl: `/images/takenori_akagi.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `hisashi_mitsui`,
    name: `Hisashi Mitsui`,
    anime: `Slam Dunk`,
    genre: `Deportes`,
    debutYear: 1990,
    studio: `Toei Animation`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Slam Dunk.`,
    imageUrl: `/images/hisashi_mitsui.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `ryota_miyagi`,
    name: `Ryota Miyagi`,
    anime: `Slam Dunk`,
    genre: `Deportes`,
    debutYear: 1990,
    studio: `Toei Animation`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Slam Dunk.`,
    imageUrl: `/images/ryota_miyagi.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `tetsuya_kuroko`,
    name: `Tetsuya Kuroko`,
    anime: `Kuroko no Basket`,
    genre: `Deportes`,
    debutYear: 2008,
    studio: `Production I.G`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Kuroko no Basket.`,
    imageUrl: `/images/tetsuya_kuroko.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `daiki_aomine`,
    name: `Daiki Aomine`,
    anime: `Kuroko no Basket`,
    genre: `Deportes`,
    debutYear: 2008,
    studio: `Production I.G`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Kuroko no Basket.`,
    imageUrl: `/images/daiki_aomine.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `seijuro_akashi`,
    name: `Seijuro Akashi`,
    anime: `Kuroko no Basket`,
    genre: `Deportes`,
    debutYear: 2008,
    studio: `Production I.G`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Kuroko no Basket.`,
    imageUrl: `/images/seijuro_akashi.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `miyuki_shirogane`,
    name: `Miyuki Shirogane`,
    anime: `Kaguya-sama: Love is War`,
    genre: `Romance`,
    debutYear: 2015,
    studio: `A-1 Pictures`,
    role: `Deuteragonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Kaguya-sama: Love is War.`,
    imageUrl: `/images/miyuki_shirogane.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `chika_fujiwara`,
    name: `Chika Fujiwara`,
    anime: `Kaguya-sama: Love is War`,
    genre: `Romance`,
    debutYear: 2015,
    studio: `A-1 Pictures`,
    role: `Secundario`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de Kaguya-sama: Love is War.`,
    imageUrl: `/images/chika_fujiwara.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `yu_ishigami`,
    name: `Yu Ishigami`,
    anime: `Kaguya-sama: Love is War`,
    genre: `Romance`,
    debutYear: 2015,
    studio: `A-1 Pictures`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Kaguya-sama: Love is War.`,
    imageUrl: `/images/yu_ishigami.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `hiro`,
    name: `Hiro`,
    anime: `Darling in the Franxx`,
    genre: `Romance`,
    debutYear: 2018,
    studio: `Trigger / A-1 Pictures`,
    role: `Deuteragonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Darling in the Franxx.`,
    imageUrl: `/images/hiro.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `shinji_ikari`,
    name: `Shinji Ikari`,
    anime: `Neon Genesis Evangelion`,
    genre: `Otros`,
    debutYear: 1995,
    studio: `Gainax`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Neon Genesis Evangelion.`,
    imageUrl: `/images/shinji_ikari.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `misato_katsuragi`,
    name: `Misato Katsuragi`,
    anime: `Neon Genesis Evangelion`,
    genre: `Otros`,
    debutYear: 1995,
    studio: `Gainax`,
    role: `Secundario`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de Neon Genesis Evangelion.`,
    imageUrl: `/images/misato_katsuragi.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `happy`,
    name: `Happy`,
    anime: `Fairy Tail`,
    genre: `Shonen`,
    debutYear: 2006,
    studio: `A-1 Pictures`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Otro`,
    debutInfo: `Personaje de Fairy Tail.`,
    imageUrl: `/images/happy.png`,
    ageDebutGroup: `Niño`,
    ageMainGroup: `Niño`,
    active: true,
  },
  {
    id: `asta`,
    name: `Asta`,
    anime: `Black Clover`,
    genre: `Shonen`,
    debutYear: 2015,
    studio: `Studio Pierrot`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Black Clover.`,
    imageUrl: `/images/asta.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `yuno`,
    name: `Yuno`,
    anime: `Black Clover`,
    genre: `Shonen`,
    debutYear: 2015,
    studio: `Studio Pierrot`,
    role: `Deuteragonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Black Clover.`,
    imageUrl: `/images/yuno.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `rintaro_okabe`,
    name: `Rintaro Okabe`,
    anime: `Steins;Gate`,
    genre: `Otros`,
    debutYear: 2009,
    studio: `White Fox`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Steins;Gate.`,
    imageUrl: `/images/rintaro_okabe.png`,
    ageDebutGroup: `Joven`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `kurisu_makise`,
    name: `Kurisu Makise`,
    anime: `Steins;Gate`,
    genre: `Otros`,
    debutYear: 2009,
    studio: `White Fox`,
    role: `Deuteragonista`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de Steins;Gate.`,
    imageUrl: `/images/kurisu_makise.png`,
    ageDebutGroup: `Joven`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `mayuri_shiina`,
    name: `Mayuri Shiina`,
    anime: `Steins;Gate`,
    genre: `Otros`,
    debutYear: 2009,
    studio: `White Fox`,
    role: `Secundario`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de Steins;Gate.`,
    imageUrl: `/images/mayuri_shiina.png`,
    ageDebutGroup: `Joven`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `subaru_natsuki`,
    name: `Subaru Natsuki`,
    anime: `Re:Zero`,
    genre: `Otros`,
    debutYear: 2014,
    studio: `White Fox`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Re:Zero.`,
    imageUrl: `/images/subaru_natsuki.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `rem`,
    name: `Rem`,
    anime: `Re:Zero`,
    genre: `Otros`,
    debutYear: 2014,
    studio: `White Fox`,
    role: `Secundario`,
    gender: `Femenino`,
    race: `Otro`,
    debutInfo: `Personaje de Re:Zero.`,
    imageUrl: `/images/rem.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `ram`,
    name: `Ram`,
    anime: `Re:Zero`,
    genre: `Otros`,
    debutYear: 2014,
    studio: `White Fox`,
    role: `Secundario`,
    gender: `Femenino`,
    race: `Otro`,
    debutInfo: `Personaje de Re:Zero.`,
    imageUrl: `/images/ram.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `kirito`,
    name: `Kirito`,
    anime: `Sword Art Online`,
    genre: `Shonen`,
    debutYear: 2009,
    studio: `A-1 Pictures`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Sword Art Online.`,
    imageUrl: `/images/kirito.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `asuna`,
    name: `Asuna`,
    anime: `Sword Art Online`,
    genre: `Shonen`,
    debutYear: 2009,
    studio: `A-1 Pictures`,
    role: `Deuteragonista`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de Sword Art Online.`,
    imageUrl: `/images/asuna.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `sinon`,
    name: `Sinon`,
    anime: `Sword Art Online`,
    genre: `Shonen`,
    debutYear: 2009,
    studio: `A-1 Pictures`,
    role: `Secundario`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de Sword Art Online.`,
    imageUrl: `/images/sinon.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `saber`,
    name: `Saber`,
    anime: `Fate/stay night`,
    genre: `Otros`,
    debutYear: 2004,
    studio: `Ufotable`,
    role: `Protagonista`,
    gender: `Femenino`,
    race: `Otro`,
    debutInfo: `Personaje de Fate/stay night.`,
    imageUrl: `/images/saber.png`,
    ageDebutGroup: `Joven`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `rin_tohsaka`,
    name: `Rin Tohsaka`,
    anime: `Fate/stay night`,
    genre: `Otros`,
    debutYear: 2004,
    studio: `Ufotable`,
    role: `Deuteragonista`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de Fate/stay night.`,
    imageUrl: `/images/rin_tohsaka.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `archer`,
    name: `Archer`,
    anime: `Fate/stay night`,
    genre: `Otros`,
    debutYear: 2004,
    studio: `Ufotable`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Otro`,
    debutInfo: `Personaje de Fate/stay night.`,
    imageUrl: `/images/archer.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `gintoki_sakata`,
    name: `Gintoki Sakata`,
    anime: `Gintama`,
    genre: `Shonen`,
    debutYear: 2003,
    studio: `Sunrise`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Gintama.`,
    imageUrl: `/images/gintoki_sakata.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `kagura`,
    name: `Kagura`,
    anime: `Gintama`,
    genre: `Shonen`,
    debutYear: 2003,
    studio: `Sunrise`,
    role: `Deuteragonista`,
    gender: `Femenino`,
    race: `Otro`,
    debutInfo: `Personaje de Gintama.`,
    imageUrl: `/images/kagura.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `shinpachi_shimura`,
    name: `Shinpachi Shimura`,
    anime: `Gintama`,
    genre: `Shonen`,
    debutYear: 2003,
    studio: `Sunrise`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Gintama.`,
    imageUrl: `/images/shinpachi_shimura.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `arataka_reigen`,
    name: `Arataka Reigen`,
    anime: `Mob Psycho 100`,
    genre: `Otros`,
    debutYear: 2012,
    studio: `Bones`,
    role: `Deuteragonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Mob Psycho 100.`,
    imageUrl: `/images/arataka_reigen.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `anya_forger`,
    name: `Anya Forger`,
    anime: `Spy x Family`,
    genre: `Otros`,
    debutYear: 2019,
    studio: `Wit Studio / CloverWorks`,
    role: `Protagonista`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de Spy x Family.`,
    imageUrl: `/images/anya_forger.png`,
    ageDebutGroup: `Niño`,
    ageMainGroup: `Niño`,
    active: true,
  },
  {
    id: `yor_forger`,
    name: `Yor Forger`,
    anime: `Spy x Family`,
    genre: `Otros`,
    debutYear: 2019,
    studio: `Wit Studio / CloverWorks`,
    role: `Deuteragonista`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de Spy x Family.`,
    imageUrl: `/images/yor_forger.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `denji`,
    name: `Denji`,
    anime: `Chainsaw Man`,
    genre: `Shonen`,
    debutYear: 2018,
    studio: `MAPPA`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Chainsaw Man.`,
    imageUrl: `/images/denji.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `power`,
    name: `Power`,
    anime: `Chainsaw Man`,
    genre: `Shonen`,
    debutYear: 2018,
    studio: `MAPPA`,
    role: `Deuteragonista`,
    gender: `Femenino`,
    race: `Demonio`,
    debutInfo: `Personaje de Chainsaw Man.`,
    imageUrl: `/images/power.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `makima`,
    name: `Makima`,
    anime: `Chainsaw Man`,
    genre: `Shonen`,
    debutYear: 2018,
    studio: `MAPPA`,
    role: `Antagonista`,
    gender: `Femenino`,
    race: `Demonio`,
    debutInfo: `Personaje de Chainsaw Man.`,
    imageUrl: `/images/makima.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `aki_hayakawa`,
    name: `Aki Hayakawa`,
    anime: `Chainsaw Man`,
    genre: `Shonen`,
    debutYear: 2018,
    studio: `MAPPA`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Chainsaw Man.`,
    imageUrl: `/images/aki_hayakawa.png`,
    ageDebutGroup: `Joven`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `ash_ketchum`,
    name: `Ash Ketchum`,
    anime: `Pokemon`,
    genre: `Otros`,
    debutYear: 1997,
    studio: `OLM`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Pokemon.`,
    imageUrl: `/images/ash_ketchum.png`,
    ageDebutGroup: `Niño`,
    ageMainGroup: `Niño`,
    active: true,
  },
  {
    id: `pikachu`,
    name: `Pikachu`,
    anime: `Pokemon`,
    genre: `Otros`,
    debutYear: 1997,
    studio: `OLM`,
    role: `Deuteragonista`,
    gender: `Otro`,
    race: `Otro`,
    debutInfo: `Personaje de Pokemon.`,
    imageUrl: `/images/pikachu.png`,
    ageDebutGroup: `Niño`,
    ageMainGroup: `Niño`,
    active: true,
  },
  {
    id: `misty`,
    name: `Misty`,
    anime: `Pokemon`,
    genre: `Otros`,
    debutYear: 1997,
    studio: `OLM`,
    role: `Secundario`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de Pokemon.`,
    imageUrl: `/images/misty.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `brock`,
    name: `Brock`,
    anime: `Pokemon`,
    genre: `Otros`,
    debutYear: 1997,
    studio: `OLM`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Pokemon.`,
    imageUrl: `/images/brock.png`,
    ageDebutGroup: `Joven`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `jessie`,
    name: `Jessie`,
    anime: `Pokemon`,
    genre: `Otros`,
    debutYear: 1997,
    studio: `OLM`,
    role: `Antagonista`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de Pokemon.`,
    imageUrl: `/images/jessie.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `james`,
    name: `James`,
    anime: `Pokemon`,
    genre: `Otros`,
    debutYear: 1997,
    studio: `OLM`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Pokemon.`,
    imageUrl: `/images/james.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `meowth`,
    name: `Meowth`,
    anime: `Pokemon`,
    genre: `Otros`,
    debutYear: 1997,
    studio: `OLM`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Otro`,
    debutInfo: `Personaje de Pokemon.`,
    imageUrl: `/images/meowth.png`,
    ageDebutGroup: `Niño`,
    ageMainGroup: `Niño`,
    active: true,
  },
  {
    id: `giovanni`,
    name: `Giovanni`,
    anime: `Pokemon`,
    genre: `Otros`,
    debutYear: 1997,
    studio: `OLM`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Pokemon.`,
    imageUrl: `/images/giovanni.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `seiya`,
    name: `Seiya`,
    anime: `Saint Seiya`,
    genre: `Shonen`,
    debutYear: 1986,
    studio: `Toei Animation`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Saint Seiya.`,
    imageUrl: `/images/seiya.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `shiryu`,
    name: `Shiryu`,
    anime: `Saint Seiya`,
    genre: `Shonen`,
    debutYear: 1986,
    studio: `Toei Animation`,
    role: `Deuteragonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Saint Seiya.`,
    imageUrl: `/images/shiryu.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `hyoga`,
    name: `Hyoga`,
    anime: `Saint Seiya`,
    genre: `Shonen`,
    debutYear: 1986,
    studio: `Toei Animation`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Saint Seiya.`,
    imageUrl: `/images/hyoga.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `shun`,
    name: `Shun`,
    anime: `Saint Seiya`,
    genre: `Shonen`,
    debutYear: 1986,
    studio: `Toei Animation`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Saint Seiya.`,
    imageUrl: `/images/shun.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `ikki`,
    name: `Ikki`,
    anime: `Saint Seiya`,
    genre: `Shonen`,
    debutYear: 1986,
    studio: `Toei Animation`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Saint Seiya.`,
    imageUrl: `/images/ikki.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `athena`,
    name: `Athena`,
    anime: `Saint Seiya`,
    genre: `Shonen`,
    debutYear: 1986,
    studio: `Toei Animation`,
    role: `Secundario`,
    gender: `Femenino`,
    race: `Dios`,
    debutInfo: `Personaje de Saint Seiya.`,
    imageUrl: `/images/athena.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `hades`,
    name: `Hades`,
    anime: `Saint Seiya`,
    genre: `Shonen`,
    debutYear: 1986,
    studio: `Toei Animation`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Dios`,
    debutInfo: `Personaje de Saint Seiya.`,
    imageUrl: `/images/hades.png`,
    ageDebutGroup: `Mayor`,
    ageMainGroup: `Mayor`,
    active: true,
  },
  {
    id: `kazuma_kuwabara`,
    name: `Kazuma Kuwabara`,
    anime: `Yu Yu Hakusho`,
    genre: `Shonen`,
    debutYear: 1990,
    studio: `Studio Pierrot`,
    role: `Deuteragonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Yu Yu Hakusho.`,
    imageUrl: `/images/kazuma_kuwabara.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `hiei`,
    name: `Hiei`,
    anime: `Yu Yu Hakusho`,
    genre: `Shonen`,
    debutYear: 1990,
    studio: `Studio Pierrot`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Otro`,
    debutInfo: `Personaje de Yu Yu Hakusho.`,
    imageUrl: `/images/hiei.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `toguro`,
    name: `Toguro`,
    anime: `Yu Yu Hakusho`,
    genre: `Shonen`,
    debutYear: 1990,
    studio: `Studio Pierrot`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Demonio`,
    debutInfo: `Personaje de Yu Yu Hakusho.`,
    imageUrl: `/images/toguro.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `inuyasha`,
    name: `Inuyasha`,
    anime: `Inuyasha`,
    genre: `Shonen`,
    debutYear: 1996,
    studio: `Sunrise`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Demonio`,
    debutInfo: `Personaje de Inuyasha.`,
    imageUrl: `/images/inuyasha.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `kagome_higurashi`,
    name: `Kagome Higurashi`,
    anime: `Inuyasha`,
    genre: `Shonen`,
    debutYear: 1996,
    studio: `Sunrise`,
    role: `Deuteragonista`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de Inuyasha.`,
    imageUrl: `/images/kagome_higurashi.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `sesshomaru`,
    name: `Sesshomaru`,
    anime: `Inuyasha`,
    genre: `Shonen`,
    debutYear: 1996,
    studio: `Sunrise`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Demonio`,
    debutInfo: `Personaje de Inuyasha.`,
    imageUrl: `/images/sesshomaru.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `naraku`,
    name: `Naraku`,
    anime: `Inuyasha`,
    genre: `Shonen`,
    debutYear: 1996,
    studio: `Sunrise`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Demonio`,
    debutInfo: `Personaje de Inuyasha.`,
    imageUrl: `/images/naraku.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `shippo`,
    name: `Shippo`,
    anime: `Inuyasha`,
    genre: `Shonen`,
    debutYear: 1996,
    studio: `Sunrise`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Otro`,
    debutInfo: `Personaje de Inuyasha.`,
    imageUrl: `/images/shippo.png`,
    ageDebutGroup: `Niño`,
    ageMainGroup: `Niño`,
    active: true,
  },
  {
    id: `kenshin_himura`,
    name: `Kenshin Himura`,
    anime: `Rurouni Kenshin`,
    genre: `Shonen`,
    debutYear: 1994,
    studio: `Studio Gallop`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Rurouni Kenshin.`,
    imageUrl: `/images/kenshin_himura.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `kaoru_kamiya`,
    name: `Kaoru Kamiya`,
    anime: `Rurouni Kenshin`,
    genre: `Shonen`,
    debutYear: 1994,
    studio: `Studio Gallop`,
    role: `Deuteragonista`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de Rurouni Kenshin.`,
    imageUrl: `/images/kaoru_kamiya.png`,
    ageDebutGroup: `Joven`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `makoto_shishio`,
    name: `Makoto Shishio`,
    anime: `Rurouni Kenshin`,
    genre: `Shonen`,
    debutYear: 1994,
    studio: `Studio Gallop`,
    role: `Antagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Rurouni Kenshin.`,
    imageUrl: `/images/makoto_shishio.png`,
    ageDebutGroup: `Adulto`,
    ageMainGroup: `Adulto`,
    active: true,
  },
  {
    id: `sanosuke_sagara`,
    name: `Sanosuke Sagara`,
    anime: `Rurouni Kenshin`,
    genre: `Shonen`,
    debutYear: 1994,
    studio: `Studio Gallop`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Rurouni Kenshin.`,
    imageUrl: `/images/sanosuke_sagara.png`,
    ageDebutGroup: `Joven`,
    ageMainGroup: `Joven`,
    active: true,
  },
  {
    id: `taichi_yagami`,
    name: `Taichi Yagami`,
    anime: `Digimon Adventure`,
    genre: `Otros`,
    debutYear: 1999,
    studio: `Toei Animation`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Digimon Adventure.`,
    imageUrl: `/images/taichi_yagami.png`,
    ageDebutGroup: `Niño`,
    ageMainGroup: `Niño`,
    active: true,
  },
  {
    id: `agumon`,
    name: `Agumon`,
    anime: `Digimon Adventure`,
    genre: `Otros`,
    debutYear: 1999,
    studio: `Toei Animation`,
    role: `Deuteragonista`,
    gender: `Masculino`,
    race: `Otro`,
    debutInfo: `Personaje de Digimon Adventure.`,
    imageUrl: `/images/agumon.png`,
    ageDebutGroup: `Niño`,
    ageMainGroup: `Niño`,
    active: true,
  },
  {
    id: `yamato_ishida`,
    name: `Yamato Ishida`,
    anime: `Digimon Adventure`,
    genre: `Otros`,
    debutYear: 1999,
    studio: `Toei Animation`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Digimon Adventure.`,
    imageUrl: `/images/yamato_ishida.png`,
    ageDebutGroup: `Niño`,
    ageMainGroup: `Niño`,
    active: true,
  },
  {
    id: `gabumon`,
    name: `Gabumon`,
    anime: `Digimon Adventure`,
    genre: `Otros`,
    debutYear: 1999,
    studio: `Toei Animation`,
    role: `Secundario`,
    gender: `Masculino`,
    race: `Otro`,
    debutInfo: `Personaje de Digimon Adventure.`,
    imageUrl: `/images/gabumon.png`,
    ageDebutGroup: `Niño`,
    ageMainGroup: `Niño`,
    active: true,
  },
  {
    id: `sora_takenouchi`,
    name: `Sora Takenouchi`,
    anime: `Digimon Adventure`,
    genre: `Otros`,
    debutYear: 1999,
    studio: `Toei Animation`,
    role: `Secundario`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de Digimon Adventure.`,
    imageUrl: `/images/sora_takenouchi.png`,
    ageDebutGroup: `Niño`,
    ageMainGroup: `Niño`,
    active: true,
  },
  {
    id: `sakura_kinomoto`,
    name: `Sakura Kinomoto`,
    anime: `Cardcaptor Sakura`,
    genre: `Romance`,
    debutYear: 1996,
    studio: `Madhouse`,
    role: `Protagonista`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de Cardcaptor Sakura.`,
    imageUrl: `/images/sakura_kinomoto.png`,
    ageDebutGroup: `Niño`,
    ageMainGroup: `Niño`,
    active: true,
  },
  {
    id: `kero`,
    name: `Kero`,
    anime: `Cardcaptor Sakura`,
    genre: `Romance`,
    debutYear: 1996,
    studio: `Madhouse`,
    role: `Secundario`,
    gender: `Otro`,
    race: `Otro`,
    debutInfo: `Personaje de Cardcaptor Sakura.`,
    imageUrl: `/images/kero.png`,
    ageDebutGroup: `Niño`,
    ageMainGroup: `Niño`,
    active: true,
  },
  {
    id: `tomoyo_daidouji`,
    name: `Tomoyo Daidouji`,
    anime: `Cardcaptor Sakura`,
    genre: `Romance`,
    debutYear: 1996,
    studio: `Madhouse`,
    role: `Secundario`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de Cardcaptor Sakura.`,
    imageUrl: `/images/tomoyo_daidouji.png`,
    ageDebutGroup: `Niño`,
    ageMainGroup: `Niño`,
    active: true,
  },
  {
    id: `kousei_arima`,
    name: `Kousei Arima`,
    anime: `Your Lie in April`,
    genre: `Romance`,
    debutYear: 2011,
    studio: `A-1 Pictures`,
    role: `Protagonista`,
    gender: `Masculino`,
    race: `Humano`,
    debutInfo: `Personaje de Your Lie in April.`,
    imageUrl: `/images/kousei_arima.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
  {
    id: `kaori_miyazono`,
    name: `Kaori Miyazono`,
    anime: `Your Lie in April`,
    genre: `Romance`,
    debutYear: 2011,
    studio: `A-1 Pictures`,
    role: `Deuteragonista`,
    gender: `Femenino`,
    race: `Humano`,
    debutInfo: `Personaje de Your Lie in April.`,
    imageUrl: `/images/kaori_miyazono.png`,
    ageDebutGroup: `Adolescente`,
    ageMainGroup: `Adolescente`,
    active: true,
  },
]
